<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');
$head = 'Create Schedule';
$this->headTitle($head);
?>

<h1><?php echo $this->translate("Create Schedule?"); ?></h1>
<p><?php echo $this->translate("This will create a match plan for all players.");?><br/>
<?php echo $this->translate("Afterwards you will have to activate the new season.");?>
</p>

<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();

