<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');
$head = 'Create Schedule';
$this->headTitle($head);
?>

<h1><?php echo $this->translate("Create Schedule?"); ?></h1>
<p><?php echo $this->translate("This is the final step of a new season.");?><br/>
<?php echo $this->translate("All participating players will receive their match schedule by email.");?><br/>
<?php echo $this->translate("The new season will automatically become active.");?>
</p>

<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();

