<?php
$title = 'Participants';
$this->headTitle($title);
/* @var $match \Season\Entity\Match */
?>

<?php $this->placeholder('noseason')->captureStart();?>
<h3><?php echo $this->translate('No players found')?></h3>
<?php $this->placeholder('noseason')->captureEnd(); ?>

<?php $this->placeholder('schedule')->captureStart();?>
<table class="table" style="margin-top: 0.5em;">
<tr>
    <th>day</th>
    <th>liga</th>
    <th>date</th>
    <th>blackId</th>
    <th>black</th>
    <th>whiteId</th>
    <th>white</th>
</tr>

<?php foreach ($this->schedule as $match) : ?>
<tr style="background-color:<?php
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $match->getMatchingDay()->getMatchDay();?></td>
    <td><?php echo $match->getLeague()->getTitle();?></td>
    <td><?php echo $match->getDate()->format('D, d.m.Y H:i');?></td>
    <td><?php echo $match->getBlack()->getId();?></td>
    <td><?php echo $match->getBlack()->getPlayer()->getShortName();?></td>
    <td><?php echo $match->getWhite()->getId();?></td>
    <td><?php echo $match->getWhite()->getPlayer()->getShortName();?></td>
</tr>
<?php endforeach; ?>
</table>
<?php $this->placeholder('schedule')->captureEnd();?>

<?php $this->placeholder('players')->captureStart();?>
<h3><?php echo $this->escapeHtml(
                $this->translate('Participants of the new Season'));
 ?></h3>

<table class="table" style="margin-top: 0.5em;">
<tr>
    <th title="<?php echo $this->translate("player's name"); ?>"><?php
        echo $this->translate("Name"); ?></th>
    <th title="<?php echo $this->translate("number of league"); ?>"><?php
        echo $this->translate("League"); ?></th>
</tr>

<?php foreach ($this->players as $user) : ?>
<tr style="background-color:<?php
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $this->escapeHtml($user->getPlayer()->getName());?></td>
    <td><?php echo $this->escapeHtml($user->getLeague()->getNumber());?></td>
</tr>
<?php endforeach; ?>
</table>
<?php $this->placeholder('players')->captureEnd();

  if($this->players!=null)
      echo $this->placeholder('players');
  else echo $this->placeholder('noseason');

if($this->schedule!=null)
      echo $this->placeholder('schedule');
  else echo $this->placeholder('noseason');


