<?php if ($this->pageCount): ?>
    <div class="matchDayPagination">
        <ul class="nakadePagination nakadePagination-centered">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li title="<?php echo $this->translate('previous'); ?>">
                    <a href="<?php echo $this->pagingUrl($this->previous); ?>">&laquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">&laquo;</a>
                </li>
            <?php
endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li title="<?php echo $this->translate('click'); ?>">
                        <a href="<?php echo $this->pagingUrl($page);?>"><?php echo $page; ?></a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php
endif; ?>
            <?php
endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li title="<?php echo $this->translate('next'); ?>">
                    <a href="<?php echo $this->pagingUrl($this->next); ?>">&raquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">&raquo;</a>
                </li>
            <?php
endif; ?>
        </ul>
    </div>
<?php
endif;