<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('User');
$title = $this->translate('Profile');
$this->headTitle($title);
/* @var $profile \User\Entity\User */
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table profile">
<tr>
    <td><?php echo $this->translate("Name:");?></td>
    <td><?php echo $this->escapeHtml($this->name);?></td>
    <td></td>
</tr>
<tr>
    <td><?php echo $this->translate("Birthday:");?></td>
    <td><?php echo $this->showDate($profile->getBirthday()); ?></td>
    <td class="edit">
        <a class="button edit" title="<?php echo $this->translate("edit");?>"
           href="<?php echo $this->url('profile', array('action' => 'birthday'));?>"></a>
    </td>
</tr>
<tr>
    <td><?php echo $this->translate("Nick:");?></td>
    <td>
        <span class="<?php echo $this->showAnonymous($profile->isAnonymous()); ?>">
            <?php echo $profile->getNickname(); ?>
        </span>
    </td>
    <td class="edit">
        <a class="button edit" title="<?php echo $this->translate("edit");?>"
           href="<?php echo $this->url('profile', array('action' => 'nick'));?>"></a>
    </td>
</tr>
<tr>
    <td><?php echo $this->translate("email:");?></td>
    <td><?php echo $profile->getEmail();  ?></td>
    <td class="edit">
        <a class="button edit" title="<?php echo $this->translate("edit");?>"
           href="<?php echo $this->url('profile', array('action' => 'email'));?>"></a>
    </td>
</tr>
<tr>
    <td><?php echo $this->translate("KGS:");?></td>
    <td><?php echo $profile->getKgs();  ?></td>
    <td class="edit">
        <a class="button edit" title="<?php echo $this->translate("edit");?>"
           href="<?php echo $this->url('profile', array('action' => 'kgs'));?>"></a>
    </td>
</tr>
<tr>
    <td><?php echo $this->translate("Username:");?></td>
    <td><?php echo $this->escapeHtml($this->username);?></td>
    <td></td>
</tr>
<tr>
    <td><?php echo $this->translate("Password");?></td>
    <td><span class="pwdInfo"><?php echo $this->showPwdInfo($profile->getCreated()); ?></span></td>
    <td class="edit">
        <a class="button edit" title="<?php echo $this->translate("edit");?>"
           href="<?php echo $this->url('profile', array('action' => 'password'));?>"></a>
    </td>
</tr>
<tr>
    <td><?php echo $this->translate("Language");?></td>
    <td><?php echo $this->showLanguage($profile->getLanguage());  ?></td>
    <td class="edit">
        <a class="button edit" title="<?php echo $this->translate("edit");?>"
           href="<?php echo $this->url('profile', array('action' => 'language'));?>"></a>
    </td>
</tr>

</table>
