<?php
$this->plugin('translate')->setTranslatorTextDomain('User');
$title = $this->translate('Edit Profile');
$this->headTitle($title);
?>
<div class="widget">
    <h3><?php echo $this->escapeHtml($title); ?></h3>


    <?php
    $this->form->prepare();
    echo $this->form()->openTag($this->form);
    echo $this->formCollection($this->form);
    echo $this->form()->closeTag();
    ?>
</div>
