<?php /* menu label dummy for poedit */ ?>

<span style="display:none">
    <?php

    $this->translate('Rules');
    $this->translate('Terms of Use');
    $this->translate('Imprint');
    $this->translate('Contact');
    $this->translate('Location');
    $this->translate('Home');
    $this->translate('Profile');
    $this->translate('Dashboard');
    $this->translate('Messages');
    $this->translate('Inbox');
    $this->translate('New Message');
    $this->translate('Outbox');
    $this->translate('League');
    $this->translate('Schedule');
    $this->translate('Standings');
    $this->translate('Enter Result');
    $this->translate('Moderator');
    $this->translate('New Season');
    $this->translate('My Manager');
    $this->translate('Edit Match Day');
    $this->translate('Edit Result');
    $this->translate('Arbitration');
    $this->translate('Admin');
    $this->translate('User');
    $this->translate('Coupons');
    $this->translate('Referees');
    $this->translate('Open Results');
    $this->translate('Edit Match Day');
    $this->translate('Appointments');
    $this->translate('Support');
    $this->translate('My Tickets');
    $this->translate('League Manager');
    $this->translate('Admin');
    $this->translate('Referee');
    $this->translate('Logout');
    $this->translate('Tickets');
    $this->translate('Shift Date');
    $this->translate('Confirm');
    $this->translate('FAQ');


    ?>
</span>
