<?php /* @var $page \Zend\Navigation\Page\AbstractPage */
$this->plugin('translate')->setTranslatorTextDomain('Application');
?>
<div class="widget">
    <div>
        <div title="<?php echo $this->translate("Logged in as"); ?>" class="infoBtn status-16 status-online-16 btnCenter"></div>
        <span style="text-indent: 5px"><?php echo $this->identity()->getUsername()?></span>
        <a href="<?php echo $this->url('login', array('action' => 'logout'))?>">
            <?php echo $this->translate("LogOut") ?>
        </a>
    </div>

    <div class="profile">
        <a href="<?php echo $this->url('profile')?>">
            <?php echo $this->translate("Edit Profile") ?>
            <div class="infoBtn status-16 user-16 btnCenter"></div>
        </a>
    </div>

    <div class="stats">
        <a href="<?php echo $this->url('stats')?>" title="<?php echo $this->translate("go to match statistics");?>">
            <div class="infoBtn nakade-16 stats-16 btnCenter"></div><?php echo $this->translate("Match Statistics") ?>
        </a>
    </div>

    <ul>
        <?php  if (!is_null($this->nextMatch())) : ?>
            <li class="nextMatch" title="<?php echo $this->translate("time left to your next match"); ?>">
                <a href="<?php echo $this->url('timeTable', array('action' => 'schedule'))?>"
                   title="<?php echo $this->translate("go to schedule"); ?>">
                    <div class="infoBtn nakade-16 match-16 btnCenter"></div>
                    <em><?php echo $this->translate("Next match");?></em>
                </a>
                <span id="MyCountdown" class="info"><?php echo $this->nextMatch()->format('d.m.Y-H:i'); ?></span>
            </li>
            <script type="text/javascript" >

                var phpDateTime = $('#MyCountdown').text();

                //split date and time
                var parts = phpDateTime.split("-");
                var dateParts = parts[0].split(".");
                var timeParts = parts[1].split(":");
                var nextMatch = new Date(dateParts[2], (dateParts[1] - 1), dateParts[0], timeParts[0], timeParts[1]);

                $('#MyCountdown').countdown({until: nextMatch, compact: true, format: 'dHms', significant: 4});

            </script>
        <?php endif; ?>

        <li>
            <a href="<?php echo $this->url('message')?>" title="<?php echo $this->translate("go to mailbox"); ?>">
                <div class="infoBtn mail-16 mail-yellow-16 btnCenter"></div>
                <span class="info"><?php echo $this->noMessage(); ?></span>
                <em><?php echo ' ' . $this->translate("new mails"); ?></em>
            </a>
        </li>

        <li>
            <a href="<?php echo $this->url('appointmentShow')?>" title="<?php echo $this->translate("go to confirmation"); ?>">
                <div class="infoBtn buttons-16 date-16"></div>
                <span class="info"><?php echo $this->noAppointment(); ?></span>
                <em><?php echo ' ' . $this->translate("open appointments"); ?></em>
            </a>
        </li>

        <li>
            <a href="<?php echo $this->url('support')?>" title="<?php echo $this->translate("go to tickets"); ?>">
                <div class="infoBtn mail-16 time-16"></div>
                <span class="info"><?php echo $this->noWaitingTicket(); ?></span>
                <em><?php echo ' ' . $this->translate("waiting tickets"); ?></em>
            </a>
        </li>


        <?php if (date('c') < date('c', strtotime('12/31/2014'))) :?>
            <li>
                <a href="<?php echo $this->url('coupon')?>" title="<?php echo $this->translate("go to invitation"); ?>">
                    <div class="infoBtn buttons-16 info-16 btnCenter"></div>
                    <span class="info"><?php echo $this->noInvited(); ?></span>
                    <em><?php echo ' ' . $this->translate("friends invited"); ?></em>
                </a>
            </li>
        <?php endif; ?>

        <?php if ($this->myOpenResult()>0) :?>
            <li>
                <a href="<?php echo $this->url('result', array('action' => 'myResult'))?>" title="<?php echo $this->translate("go to results"); ?>">
                    <div class="infoBtn buttons-16 exclamation-16 btnCenter"></div>
                    <span class="info"><?php echo $this->myOpenResult(); ?></span>
                    <em><?php echo ' ' . $this->translate("open results"); ?></em>
                </a>
            </li>
        <?php endif; ?>
    </ul>

    <?php if ($this->isManager()) : ?>
        <div class="moderator">
            <div>
                <div class="infoBtn status-16 support-16 btnCenter"></div><?php echo $this->translate("Moderator"); ?>
            </div>

            <a href="<?php echo $this->url('ticket')?>" title="<?php echo $this->translate("go to tickets"); ?>">
                <div class="infoBtn buttons-16 exclamation-16 btnCenter"></div>
                <span class="info"><?php echo $this->noModeratorTicket(); ?></span>
                <em><?php echo ' ' . $this->translate("open tickets"); ?></em>
            </a>
        </div>
    <?php endif; ?>


</div>





