<?php /* @var $page \Zend\Navigation\Page\AbstractPage */
$this->plugin('translate')->setTranslatorTextDomain('Application');
?>
<div class="widget">
    <div>
        <div title="<?php echo $this->translate("Logged in as"); ?>" class="infoBtn status-16 status-online-16 btnCenter"></div>
        <span style="text-indent: 5px"><?php echo $this->identity()->getUsername()?></span>
        <a href="<?php echo $this->url('login', array('action' => 'logout'))?>">
            <?php echo $this->translate("LogOut") ?>
        </a>
    </div>

    <div class="profile">
        <a href="<?php echo $this->url('profile')?>">
            <?php echo $this->translate("Edit Profile") ?>
            <div class="infoBtn status-16 user-16 btnCenter"></div>
        </a>
    </div>

    <ul>
    <li><?php echo $this->translate("You have ") . ' '; ?><span class="info"><?php echo $this->noMessage(); ?></span>
            <a href="<?php echo $this->url('message')?>" title="<?php echo $this->translate("go to mailbox"); ?>">
                <?php echo ' ' . $this->translate("new mails"); ?>
                <div class="infoBtn mail-16 mail-yellow-16 btnCenter"></div>
            </a>
    </li>

    <li>
        <?php echo $this->translate("You have ") . ' '; ?><span class="info"><?php echo $this->noAppointment(); ?></span>
        <a href="<?php echo $this->url('appointmentShow')?>" title="<?php echo $this->translate("go to confirmation"); ?>">
            <?php echo ' ' . $this->translate("open appointments"); ?>
            <div class="infoBtn mail-16 time-16"></div>
        </a>
    </li>

    <li>
        <?php echo $this->translate("You have ") . ' '; ?><span class="info"><?php echo $this->noWaitingTicket(); ?></span>
        <a href="<?php echo $this->url('support')?>" title="<?php echo $this->translate("go to tickets"); ?>">
            <?php echo ' ' . $this->translate("waiting tickets"); ?>
            <div class="infoBtn mail-16 time-16"></div>
        </a>
    </li>


    <?php if (date('c') < date('c', strtotime('12/31/2014'))) :?>
    <li>
        <?php echo $this->translate("You have ") . ' '; ?><span class="info"><?php echo $this->noInvited(); ?></span>
        <a href="<?php echo $this->url('coupon')?>" title="<?php echo $this->translate("go to invitation"); ?>">
            <?php echo ' ' . $this->translate("friends invited"); ?>
            <div class="infoBtn buttons-16 info-16 btnCenter"></div>
        </a>
    </li>
    <?php endif; ?>
    </ul>

    <?php if ($this->isManager()) : ?>
    <div class="moderator">
        <div><div class="infoBtn status-16 support-16 btnCenter"></div><?php echo $this->translate("Moderator"); ?></div>
        <?php echo $this->translate("You have ") . ' '; ?><span class="info"><?php echo $this->noModeratorTicket(); ?></span>
        <a href="<?php echo $this->url('ticket')?>" title="<?php echo $this->translate("go to tickets"); ?>">
            <?php echo ' ' . $this->translate("open tickets"); ?>
            <div class="infoBtn buttons-16 exclamation-16 btnCenter"></div>
        </a>
    </div>
    <?php endif; ?>


</div>