<?php  /* @var $page \Zend\Navigation\Page\AbstractPage */?>
<ul class="dropdown-menu">
    <?php foreach ($this->pages as $page) : ?>
        <?php if ($page->isVisible() && $this->isAllowed($page->getPrivilege())) :?>
            <li <?php if ($page->isActive()) : ?>class="active"<?php endif; ?>>
                <a href="<?php echo $page->getHref();?>">
                    <?php echo $this->translate($page->getLabel()); ?>
                </a>
            </li>
        <?php endif;?>
    <?php endforeach; ?>
</ul>