<?php /* @var $page \Zend\Navigation\Page\AbstractPage */
/* @var $subPage \Zend\Navigation\Page\AbstractPage */
$this->plugin('translate')->setTranslatorTextDomain('Application');
?>

<div class="nav-collapse">
    <ul class="nav">
        <?php foreach ($this->container as $page) : ?>
            <?php if ($page->isVisible() && $this->isAllowed($page->getPrivilege())) : ?>
                <?php   if ($page->hasPages()) : ?>
                    <li class="dropdown">
                        <a  class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <?php echo $this->translate($page->getLabel()); ?>
                            <b class="caret"></b>
                        </a>
                        <?php
                        echo $this->partialLoop('subMenu',
                            array(array('pages' => $page->getPages())));  ?>
                    </li>
                <?php else : ?>
                    <li <?php if ($page->isActive()) : ?>class="active"<?php endif; ?>>
                        <a  href="<?php echo $page->getHref(); ?>"><?php
                            echo $this->translate($page->getLabel()) ?></a>
                    </li>
                <?php endif; ?>
            <?php endif;?>
        <?php endforeach; ?>
        <?php if (!$this->identity()) : ?>
            <li>
                <a href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('LogIn') ?></a>
            </li>
        <?php endif; ?>
    </ul>
</div>
