<?php
// module/Impressum/view/impressum/impressum/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('Blog'); 
$title = $this->translate("News");
$this->headTitle($title);
?>

<div style="height:9em;width:80%; overflow:auto">
<?php foreach ($blog as $post) : ?>
<div style="padding:.5em;">
    <h3><?php echo $post->title;?></h3>
    <p style="font-size:13px;line-height:1.3;"><?php echo $post->content;?></br>
    <span style="color:grey; font-size:smaller;line-height:0;padding:0;">gepostet am <?php echo $post->date;?></span>
    </p>
</div>
<?php endforeach; ?>
</div>

