<?php
//module/Authentication/view/authentication/auth/login.phtml
$this->plugin('translate')->setTranslatorTextDomain('Auth');

$form = $this->form;
$form->setAttribute('action', $this->url(
    'login',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
<a href="<?php echo $this->url('register',
    array('action' => 'forgot'));?>"><?php echo $this->translate("Zugangsdaten vergessen?");?></a>
<?php
if ($this->messages) {
    echo '<ul>';
    foreach ($this->messages as $message) {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}