<?php
$this->plugin('translate')->setTranslatorTextDomain('League');
/* @var $match \Season\Entity\Match */
$iCalInfo = $this->translate("download your schedule calendar (iCal)");
$this->headTitle('schedule');

/* @var $this->league \Season\Entity\League */

$title = $this->translate("%NAME% League No. %NUMBER%");

if (!is_null($this->league)) {
    $title = str_replace("%NAME%", $this->league->getSeason()->getAssociation()->getName(), $title);
    $title = str_replace("%NUMBER%", $this->league->getSeason()->getNumber(), $title);
}
?>
<?php $this->placeholder('noSchedule')->captureStart();?>
    <h3><?php echo $this->translate('No schedule found')?></h3>
<?php $this->placeholder('noSchedule')->captureEnd(); ?>

<?php $this->placeholder('schedule')->captureStart();?>
    <div class="widget">
        <h3><?php echo $title; ?></h3>
        <a class="iCal" title="<?php echo $iCalInfo; ?>" href="<?php echo $this->url('timeTable', array('action' => 'iCal')); ?>">
            <?php echo $this->translate("Download your calendar"); ?>
        </a>
        <table class="league">
            <?php foreach ($this->matches as $match) : ?>
                <tr>
                    <td style="text-decoration: <?php echo $this->hasResult($match) ?>" class="space"><?php echo $match->getDate()->format('d.m. H:i');?></td>
                    <td title="<?php echo $this->translate('my color')?>" class="<?php echo $this->myColor($match); ?>"></td>
                    <td class="space"><?php echo $this->opponent($match)->getShortName(); ?> (<span style='font-weight: bold'><?php echo $this->opponent($match)->getOnlineName(); ?></span>)</td>
                </tr>
            <?php
            endforeach;
            ?>
        </table>
    </div>
<?php $this->placeholder('schedule')->captureEnd();

if (is_null($this->league)) {
    echo $this->placeholder('noSchedule');
} else {
    echo $this->placeholder('schedule');
}

