<?php $this->plugin('translate')->setTranslatorTextDomain('Application');

$title = $this->translate("Contact");
$this->headTitle()->prepend($title); ?>
<section class="contact">
<h2><?php echo $title ?></h2>

<p>
<?php echo $this->translate("Feel free to contact us."); ?>
</p>
    <span style="color:red; font-weight:bold">Currently under Construction</span>
<?php

$this->form->prepare();
echo $this->form()->openTag($this->form); ?>
<dl class="zend_form">
<dt><?php echo  $this->formLabel($form->get('from')); ?></dt>
    <dd><?php
        echo $this->formInput($form->get('from'));
        echo $this->formElementErrors($form->get('from'));
        ?></dd>

    <dt><?php echo $this->formLabel($form->get('subject')); ?></dt>
    <dd><?php
        echo $this->formInput($form->get('subject'));
        echo $this->formElementErrors($form->get('subject'));
        ?></dd>

    <dt><?php echo $this->formLabel($form->get('body')); ?></dt>
    <dd><?php
        echo $this->formTextarea($form->get('body'));
        echo $this->formElementErrors($form->get('body'));
        ?></dd>

    <dt><?php echo $this->formLabel($form->get('captcha')); ?></dt>
    <dd><?php
        echo $this->formCaptcha($form->get('captcha'));
        echo $this->formElementErrors($form->get('captcha'));
        ?></dd>

    <dd><?php
        echo $this->formElement($form->get('csrf'));
        echo $this->formInput($form->get('Send'));
        echo $this->formElementErrors($form->get('Send'));
        ?></dd>

    </dl>

<?php echo $this->form()->closeTag();?>
</section>
