<?php $this->plugin('translate')->setTranslatorTextDomain('Application');

$title = $this->translate("Contact");
$this->headTitle()->prepend($title); ?>
<h2><?php echo $title ?></h2>

<p>
<?php echo $this->translate("Feel free to contact us."); ?>
</p>

<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();
