<?php $this->plugin('translate')->setTranslatorTextDomain('Application');

$title = $this->translate("Contact");
$this->headTitle()->prepend($title); ?>
<h2><?php echo $title ?></h2>

<p>
<?php echo $this->translate("Feel free to contact us."); ?>
</p>

<?php

$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>
<dl class="zend_form">
<dt><?php echo  $this->formLabel($form->get('name')); ?></dt>
    <dd><?php
        echo $this->formInput($form->get('name'));
        echo $this->formElementErrors($form->get('name'));
        ?></dd>

    <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
    <dd><?php
        echo $this->formInput($form->get('email'));
        echo $this->formElementErrors($form->get('email'));
        ?></dd>

    <dt><?php echo $this->formLabel($form->get('message')); ?></dt>
    <dd><?php
        echo $this->formTextarea($form->get('message'));
        echo $this->formElementErrors($form->get('message'));
        ?></dd>

    <dt><?php echo $this->formLabel($form->get('captcha')); ?></dt>
    <dd><?php
        echo $this->formCaptcha($form->get('captcha'));
        echo $this->formElementErrors($form->get('captcha'));
        ?></dd>

    <dd><?php
        echo $this->formElement($form->get('csrf'));
        echo $this->formInput($form->get('Send'));
        echo $this->formElementErrors($form->get('Send'));
        ?></dd>

    </dl>

<?php echo $this->form()->closeTag();
