<?php
// module/Album/view/album/album/add.phtml:

$title = 'Neues Resultat eintragen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table style="width:25em;margin: 1em 0;">
<tr>
    <td><?php echo $game->getDate()->format('d.m.Y   H');?>h</td>
    <td><?php echo $this->escapeHtml($this->player($game->getBlack()));?></td>
    <td style="width:1em">-</td>
    <td><?php echo $this->escapeHtml($this->player($game->getWhite()));?></td>
</tr>
</table>


<?php

$form = $this->form;
$form->setAttribute(
        'action', $this->url(
                'league', 
                array(
                    'action' => 'add',
                    'id' => $id,
                )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
/*echo $this->formHidden($form->get('_id'));
echo $this->formRow($form->get('result'));
echo $this->formRow($form->get('winner'));
echo $this->formRow($form->get('points'));
echo $this->formSubmit($form->get('submit'));*/
echo $this->form()->closeTag();