<?php
// module/user/view/user/user/index.phtml:

$title = 'Top-Liga Sommer 2013';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>


<table class="table" style="width:8em;margin-top: 0.5em;">
<tr>

    <th title="Position">P</th>
    <th>Name</th>
    <th title="gespielte Partien">GP</th>
    <th title="Siegpunkte">SP</th>
    <th title="Tie-Breaker">Hahn</th>
   
</tr>
<?php foreach ($users as $user) : ?>
<tr style="background-color:<?php 
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $this->position($user); ?></td>
    <td><?php echo $this->escapeHtml($this->player($user));?></td>
    <td><?php echo $this->escapeHtml($user->getGamesPlayed());?></td>
    <td><?php echo $this->escapeHtml($user->getWin());?></td>
    <td><?php echo $this->escapeHtml($user->getTiebreaker1());?></td>
    
</tr>
<?php endforeach; ?>
</table>
