<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('League'); 

$headline = $this->translate("New Season");
$this->headTitle($headline);

?>
<h3><?php echo $this->escapeHtml($headline) ." No.".  $this->number; ?></h3>

<?php
$form = $this->form;
$form->setAttribute('action', '/newseason/add');

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}

?>
