<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');
$head = 'Activate Season';
$this->headTitle($head);
?>

<h1><?php echo $this->translate("Activate Season?"); ?></h1>
<p><?php echo $this->translate("This is the final step of a new season.");?><br/>
<?php echo $this->translate("All participating players will receive their match schedule.");?><br/>
</p>

<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();

