<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');
/* @var $season \Season\Entity\Season */
$season = $this->season;
$this->headTitle('Overview');
$title = sprintf("%s: %s %s",
    $this->translate('Create Season'),
    $this->seasonTitle($season),
    $this->translate('League'));

?>

<h2><?php echo  $title;?></h2>
<hr/>
<h4><?php echo $this->translate("Season no.") . ' ' . $season->getNumber()?></h4>
<ul class="createSeason">
    <li><?php echo $this->translate('Leagues') . ': ' . $season->getNoLeagues() ?>
        <a href="<?php echo $this->url('createLeague'); ?>" title="<?php echo "League Info" ?>"></a>
    </li>
    <li><?php echo $this->translate('Participants') . ': ' . $season->getNoPlayers() ?>
        <a href="<?php echo $this->url('invitePlayer'); ?>" title="<?php echo "Player Info" ?>"></a>
    </li>
    <li><?php echo $this->translate('Matches') . ': ' . $season->getNoMatches() ?></li>
    <li><?php echo $this->translate('First match') . ': ' . $this->matchDate($season->getFirstMatchDate()); ?></li>
    <li><?php echo $this->translate('Last match') . ': ' . $this->matchDate($season->getLastMatchDate()); ?></li>
    <li><?php echo $this->translate('State') . ': ' . $this->state($season); ?></li>
</ul>
<hr/>

<?php $this->placeholder('season')->captureStart();?>
    <a class="btn" href="<?php echo $this->url('createSeason', array('action' => 'edit')); ?>"><?php echo $this->translate("edit Season"); ?></a>
<?php $this->placeholder('season')->captureEnd(); ?>

<?php $this->placeholder('invite')->captureStart();?>
    <a class="btn" href="<?php echo $this->url('invitePlayer', array('action' => 'add')); ?>"><?php echo $this->translate("invite Player"); ?></a>
<?php $this->placeholder('invite')->captureEnd(); ?>

<?php $this->placeholder('newLeague')->captureStart();?>
    <a class="btn" href="<?php echo $this->url('createLeague', array('action' => 'add')); ?>"><?php echo $this->translate("add League"); ?></a>
<?php $this->placeholder('newLeague')->captureEnd(); ?>

<?php $this->placeholder('league')->captureStart();?>
    <a class="btn" href="<?php echo $this->url('createLeague'); ?>"><?php echo $this->translate("edit League"); ?></a>
    <a class="btn" href="<?php echo $this->url('configMatchDay', array('action' => 'add')); ?>"><?php echo $this->translate("configure Match Days"); ?></a>
<?php $this->placeholder('league')->captureEnd(); ?>

<?php $this->placeholder('matchDays')->captureStart();?>
    <a class="btn" href="<?php echo $this->url('configMatchDay'); ?>"><?php echo $this->translate("edit Match Days"); ?></a>
    <a class="btn" href="<?php echo $this->url('configMatchDay', array('action' => 'delete')); ?>"><?php echo $this->translate("remove Match Days"); ?></a>
    <a class="btn" href="<?php echo $this->url('createSchedule', array('action' => 'create')); ?>"><?php echo $this->translate("create Schedule"); ?></a>
<?php $this->placeholder('matchDays')->captureEnd(); ?>

<?php $this->placeholder('schedule')->captureStart();?>
    <a class="btn" href="<?php echo $this->url('createSchedule', array('action' => 'delete')); ?>"><?php echo $this->translate("remove Schedule"); ?></a>
    <a class="btn" href="<?php echo $this->url('createSeason', array('action' => 'activate')); ?>"><?php echo $this->translate("activate Season"); ?></a>
<?php $this->placeholder('schedule')->captureEnd(); ?>


<?php

if (!$season->hasPlayers()) {
    echo $this->placeholder('season');
}
if ($season->hasAvailablePlayers() && !$season->hasMatchDays() ) {
    echo $this->placeholder('invite');
}
if ($season->hasUnassignedPlayers() && !$season->hasMatchDays() ) {
    echo $this->placeholder('newLeague');
}
if ($season->hasLeagues() && !$season->hasMatchDays() ) {
    echo $this->placeholder('league');
}
if ($season->hasSchedule() ) {
    echo $this->placeholder('schedule');
}
if ($season->hasMatchDays() && !$season->hasSchedule()) {
    echo $this->placeholder('matchDays');
}







