<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');
/* @var $season \Season\Entity\Season */
$season = $this->season;
$this->headTitle('Overview');
$title = sprintf("%s: %s %s",
    $this->translate('Season Overview'),
    $this->seasonTitle($season),
    $this->translate('League'));
?>

<h3><?php echo $title;?></h3>

<?php $this->placeholder('noSeason')->captureStart();?>
      <?php echo $this->translate("No season found."); ?>
<?php $this->placeholder('noSeason')->captureEnd();?>


<?php $this->placeholder('actual')->captureStart();?>

<h5><?php echo $this->translate("Season no.") . ' ' . $season->getNumber()?></h5>
<ul>
    <li><?php echo $this->translate('Number of leagues') . ': ' . $season->getNoLeagues() ?></li>
    <li><?php echo $this->translate('Number of players') . ': ' . $season->getNoPlayers() ?></li>
    <li><?php echo $this->translate('Number of matches') . ': ' . $season->getNoMatches() ?></li>
    <li><?php echo $this->translate('Open matches') . ': ' . $season->getNoOpenMatches() ?></li>
    <li><?php echo $this->translate('First match') . ': ' . $season->getFirstMatchDate()->format('d.m.Y H:i'); ?></li>
    <li><?php echo $this->translate('Last match') . ': ' . $season->getLastMatchDate()->format('d.m.Y H:i'); ?></li>
    <li><?php echo $this->translate('State') . ': ' . $this->state($season); ?></li>
</ul>

<?php $this->placeholder('actual')->captureEnd(); ?>


<?php

 if (empty($this->season)) {
     echo $this->placeholder('noSeason');
 } else {
     echo $this->placeholder('actual');
 }

