<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('League');
$title = $this->translate('Season Overview') . ' ' . $season->getTitle()->getName() . ' ' . $this->translate('League');
$this->headTitle('Overview');
/* @var $season \Season\Entity\Season */
$season = $this->season;
?>

<h3><?php echo $title;?></h3>

<?php $this->placeholder('noseason')->captureStart();?>
  <a href="/newseason/add" title="<?php echo $this->translate("create new season");?>">
      <?php echo $this->translate("create new season"); ?>
  </a>
<?php $this->placeholder('noseason')->captureEnd();?>


<?php $this->placeholder('actual')->captureStart();?>
<h5><?php echo $this->translate("Season No.") . ' ' . $season->getNumber()?></h5>
<ul>
    <li><?php echo $this->translate('Number of Leagues') . ': ' . $season->getNoLeagues() ?></li>
    <li><?php echo $this->translate('Number of Players') . ': ' . $season->getNoPlayers() ?></li>
    <li><?php echo $this->translate('Number of Matches') . ': ' . $season->getNoMatches() ?></li>
    <li><?php echo $this->translate('Open Matches') . ': ' . $season->getOpenMatches() ?></li>
    <li><?php echo $this->translate('First Match') . ': ' . $season->getFirstMatchDate()->format('d.m.Y H:i'); ?></li>
    <li><?php echo $this->translate('Last Match') . ': ' . $season->getLastMatchDate()->format('d.m.Y H:i'); ?></li>
    <li><?php echo $this->translate('State') . ': ' . $season->hasEnded(); ?></li>
</ul>

<?php $this->placeholder('actual')->captureEnd(); ?>

 <?php $this->placeholder('newseason')->captureStart();?>
 <h5><?php echo $this->translate("next season") . ':'?>
    <?php echo $this->seasontitle($this->new);
     ?></h5>
<ul>
<?php foreach ($this->newstatus as $key=> $value) : ?>
         <li><?php echo $key .': '.$value; ?></li>
 <?php endforeach; ?>
</ul>

 - empfehlung: add league | add players | move start date<br>

<?php $this->placeholder('newseason')->captureEnd();

 if($this->status!=null)
      echo $this->placeholder('actual');
 else echo $this->placeholder('noseason');

 if($this->newstatus!=null)
    echo $this->placeholder('newseason');
 else echo $this->placeholder('noseason');
?>
