<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');
/* @var $season \Season\Entity\Season */
$season = $this->season;
$this->headTitle('Rules');
$title = $this->translate('Times and Komi');
?>

<?php $this->placeholder('actual')->captureStart();?>
    <div class="widget">
        <h3><?php echo $title;?></h3>
        <table class="legend">
            <tr>
                <td><?php echo $this->translate('Time') . ': '; ?></td>
                <td class="value"><?php echo $season->getTime()->getBaseTime(); ?></td>
                <td><?php echo $this->translate('min.'); ?></td>
            </tr>
            <?php if ($season->getTime()->hasAdditionalTime()) : ?>
                <tr>
                    <td><?php echo $this->translate('Byoyomi') . ': '; ?></td>
                    <td class="value"><?php echo $season->getTime()->getMoves() . '/' . $season->getTime()->getAdditionalTime(); ?></td>
                    <td></td>
                </tr>
            <?php endif; ?>
            <tr>
                <td><?php echo $this->translate('Komi') . ': '; ?></td>
                <td class="value"><?php echo $season->getKomi(); ?></td>
                <td><?php echo $this->translate('points');?></td>
            </tr>
        </table>
    </div>
<?php $this->placeholder('actual')->captureEnd(); ?>


<?php
if (!empty($this->season)) {
    echo $this->placeholder('actual');
}

