<?php
$this->plugin('translate')->setTranslatorTextDomain('Appointment');
$title = $this->translate("Reject new match appointment");
$this->headTitle($title);

?>

<h3><?php echo $title;?></h3>
<p>
    <div><?php echo $this->translate("Please provide a reason for rejecting the new match date."); ?></div>
    <div><?php echo $this->translate("For example: I was not asked at all."); ?></div>
</p>

<table style="margin-bottom: 10px;">
<tr>
    <td style="font-weight: bold;"><?php echo $this->translate("Match"); ?>:</td>
    <td style="color:#0088cc"><?php echo $this->matchInfo; ?></td>
</tr>
<tr>
    <td style="font-weight: bold;"><?php echo $this->translate("Old Date"); ?>:</td>
    <td style="color:#0088cc; text-align: right;"><?php echo $this->oldDate; ?></td>
</tr>
<tr>
    <td style="font-weight: bold;"><?php echo $this->translate("New Date"); ?>:</td>
    <td style="color:#0088cc; text-align: right;"><?php echo $this->newDate; ?></td>
</tr>
</table>


<?php

$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();
