<?php
$this->plugin('translate')->setTranslatorTextDomain('Appointment');
$title = $this->translate("Reject new match appointment");
$this->headTitle($title);

?>

<h3><?php echo $title;?></h3>
<p>
    <?php echo $this->translate("Please provide a reason for rejecting the new match date."); ?><br/>
    <?php echo $this->translate("For example: I was not asked at all."); ?><br/>
</p>

<table class="reject">
<tr>
    <td><?php echo $this->translate("Match"); ?>:</td>
    <td><span><?php echo $this->matchInfo; ?></span></td>
</tr>
<tr>
    <td><?php echo $this->translate("Old Date"); ?>:</td>
    <td><span><?php echo $this->oldDate; ?></span></td>
</tr>
<tr>
    <td><?php echo $this->translate("New Date"); ?>:</td>
    <td><span><?php echo $this->newDate; ?></span></td>
</tr>
</table>


<?php

$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();
