<?php
$this->plugin('translate')->setTranslatorTextDomain('Appointment');
$title = $this->translate("Match appointment submitted");
$this->headTitle($title);

?>

<h3><?php echo $title;?></h3>
<p>
    <?php echo $this->translate("Your match appointment is submitted."); ?><br/>
    <?php echo $this->translate("Please show some patience until your opponent confirmed the new date."); ?><br/>
    <?php echo $this->translate("A reminder mail is sent to your email address."); ?><br/>
</p>
