<?php
$this->plugin('translate')->setTranslatorTextDomain('Appointment');
$title = $this->translate("New match appointment confirmed");
$this->headTitle($title);

?>

<h3><?php echo $title;?></h3>
<p>
    <div><?php echo $this->translate("Your match appointment is confirmed."); ?></div>
    <div><?php echo $this->translate("Further detailed information will be sent to your email address."); ?></div>
</p>
