<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('League'); 
?>

<h3><?php echo $this->escapeHtml('My Calculated Table'); ?></h3>

<?php $this->placeholder('standings')->captureStart();?>
<table class="table" style="width:8em;margin-top: 0.5em;">
<tr>
    <th title="<?php echo $this->translate('Position')?>">P</th>
    <th title="<?php echo $this->translate('Player')?>"><?php 
        echo $this->translate('Name')?></th>
    <th title="<?php echo $this->translate('Played games')?>"><?php 
        echo $this->translate('GP')?></th>
    <th title="<?php echo $this->translate('Suspende games')?>"><?php 
        echo $this->translate('GS')?></th>
    <th title="<?php echo $this->translate('Wins')?>"><?php 
        echo $this->translate('W')?></th>
     <th title="<?php echo $this->translate('Jigo')?>"><?php 
        echo $this->translate('J')?></th>
     <th title="<?php echo $this->translate('Lost')?>"><?php 
        echo $this->translate('L')?></th>
      <th title="<?php echo $this->translate('Points')?>"><?php 
        echo $this->translate('Pt')?></th>
    <th title="<?php echo $this->translate('TB1')?>"><?php 
        echo $this->translate('Hahn')?></th>
    <th title="<?php echo $this->translate('TB2')?>"><?php 
        echo $this->translate('CUSS')?></th>
</tr>
<?php foreach ($this->table as $player) : ?>
<tr style="background-color:<?php 
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $this->position($player) ?></td>
    <td><?php echo $this->escapeHtml($this->player($player->getPlayer()));?></td>
    <td><?php echo $player->getGamesPlayed(); ?></td>
    <td><?php echo $player->getGamesSuspended(); ?></td>
    <td><?php echo $player->getGamesWin();?></td>
    <td><?php echo $player->getGamesDraw();?></td>
    <td><?php echo $player->getGamesLost();?></td>
    <td><?php echo $player->getGamesPoints();?></td>
    <td><?php echo $player->getFirstTiebreak();?></td>
    <td><?php echo $player->getSecondTiebreak();?></td>
    
</tr>
<?php endforeach; ?>
</table>
<?php $this->placeholder('standings')->captureEnd(); 

  if($this->table!=null)
      echo $this->placeholder('standings');
          
        
?>


