<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('League'); 
$this->headTitle($this->title);
?>

<h3><?php echo $this->escapeHtml( $this->title); ?></h3>

<?php $this->placeholder('standings')->captureStart();?>
<table class="table" style="width:8em;margin-top: 0.5em;">
<tr>
    <th title="<?php echo $this->translate('Position');?>">No</th>
    <th title="<?php echo $this->translate('Player');?>">
        <?php echo $this->translate('Name')?></a></th>
    <th title="<?php echo $this->translate('Games')?>">
        <?php echo $this->translate('G')?></th>
    <th title="<?php echo $this->translate('Points')?>">
        <?php echo $this->translate('P')?></th>
    <th title="<?php echo $this->translate('Tiebreaker')?>">
        <?php echo $this->translate('TB')?></th>
   </tr>
<?php foreach ($this->table as $player) : ?>
<tr style="background-color:<?php 
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $this->position($player) ?></td>
    <td><?php echo $this->escapeHtml($player->getPlayer()->getShortName());?></td>
    <td><?php echo $player->getGamesPlayed(); ?></td>
    <td><?php echo $player->getGamesPoints();?></td>
    <td><?php echo $player->getFirstTiebreak();?></td>
    
</tr>
<?php endforeach; ?>
</table>
<?php $this->placeholder('standings')->captureEnd(); 

  if($this->table!=null)
      echo $this->placeholder('standings');
          
        
?>
