<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('League');


$this->headTitle('schedule');
?>
<?php $this->placeholder('noSchedule')->captureStart();?>
<h3><?php echo $this->translate('No schedule found')?></h3>
<?php $this->placeholder('noSchedule')->captureEnd(); ?>

<?php $this->placeholder('schedule')->captureStart();?>
<h3><?php echo $this->escapeHtml($this->title); ?></h3>
<a href="/actual/iCal"><img src="/images/iCal-32.png" /></a>
<table class="league">
<?php foreach ($this->matches as $match) : ?>

<?php

    /* @var $match League\Entity\Match */
    $opponent = $match->getBlack();
    if ( $opponent->getId() == $this->userId) {
        $opponent = $match->getWhite();
    }
    $opponentName = sprintf("%s (<span style='font-weight: bold'>%s</span>)",
        $opponent->getShortName(),
        $opponent->getOnlineName()
    );

    $myColor = "white";
    if ( $match->getBlack()->getId() == $this->userId) {
        $myColor = "black";
    }

    $isPlayed ='';
    if (!is_null($match->getResultId())) {
        $isPlayed = "text-decoration:line-through;";
    }


?>
<tr>
    <td style="<?php echo $isPlayed ?>" class="space"><?php echo $match->getDate()->format('d.m. H:i');?></td>
    <td title="<?php echo $this->translate('my color')?>" class="<?php echo $myColor; ?>"></td>
    <td class="space"><?php echo $opponentName; ?></td>
</tr>
<?php
endforeach;
?>
</table>
<?php $this->placeholder('schedule')->captureEnd();

  if ($this->matches != null) {
      echo $this->placeholder('schedule');
  } else {
      echo $this->placeholder('noSchedule');
  }
