<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('League'); 
?>

<h3><?php echo $this->escapeHtml($this->title); ?></h3>

<?php $this->placeholder('standings')->captureStart();
  $route  =  'actual';
  $action =  'table';
?>
<table class="table" style="width:auto;margin-top: 0.5em;">
<tr>
    <th title="<?php echo $this->translate('Position');?>">P</th>
    <th title="<?php echo $this->translate('Player');?>">
        <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'name')
                );?>">
        <?php echo $this->translate('Name')?></a></th>
    <th title="<?php echo $this->translate('played games')?>">
        <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'played')
                );?>">
        <?php echo $this->translate('GP')?></th>
    <th title="<?php echo $this->translate('Suspended games')?>">
        <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'suspended')
                );?>">
        <?php echo $this->translate('GS')?></th>
    <th title="<?php echo $this->translate('Wins')?>">
        <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'win')
                );?>">
        <?php echo $this->translate('W')?></th>
     <th title="<?php echo $this->translate('Jigo')?>">
          <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'draw')
                );?>">
        <?php echo $this->translate('J')?></th>
     <th title="<?php echo $this->translate('Lost')?>">
         <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'lost')
                );?>">
        <?php echo $this->translate('L')?></th>
      <th title="<?php echo $this->translate('Points')?>">
         <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'points')
                );?>">
        <?php echo $this->translate('Pt')?></th>
    <th title="<?php echo $this->translate('First Tiebreaker')?>">
        <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'firstTiebreak')
                );?>">
        <?php echo $this->tiebreakers[0]?></th>
    <th title="<?php echo $this->translate('Second Tiebreaker')?>">
         <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'secondTiebreak')
                );?>">
        <?php echo $this->tiebreakers[1]?></th>
    <th title="<?php echo $this->translate('Third Tiebreaker')?>">
         <a href="<?php echo $this->url(
                    $route, array('action'=>$action, 'sort'=>'thirdTiebreak')
                );?>">
       <?php echo $this->tiebreakers[2]?></th>           
</tr>
<?php foreach ($this->table as $player) : ?>
<tr style="background-color:<?php 
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $this->position($player) ?></td>
    <td><?php echo $this->escapeHtml($player->getPlayer()->getShortName());?></td>
    <td><?php echo $player->getGamesPlayed(); ?></td>
    <td><?php echo $player->getGamesSuspended(); ?></td>
    <td><?php echo $player->getGamesWin();?></td>
    <td><?php echo $player->getGamesDraw();?></td>
    <td><?php echo $player->getGamesLost();?></td>
    <td><?php echo $player->getGamesPoints();?></td>
    <td><?php echo $player->getFirstTiebreak();?></td>
    <td><?php echo $player->getSecondTiebreak();?></td>
    <td><?php echo $player->getThirdTiebreak();?></td>
    
</tr>
<?php endforeach; ?>
</table>
<?php $this->placeholder('standings')->captureEnd(); 

  if($this->table!=null)
      echo $this->placeholder('standings');
          
        
?>


