<?php
// module/Training/view/training/training/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('Training'); 
$title = $this->translate("Meeting");
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo $this->translate("Every Tuesday from 5:00 p.m. to 10:00 p.m."); ?></br>
<?php echo $this->translate("Official training of the Bundesliga team Nakade. Guests are welcome.");?></br>
</p>
 

<p style="font-weight:bold;"><?php echo $this->escapeHtml("Haus der Jugend Charlottenburg - Zillestraße 54 - 10585 Berlin"); ?></p>


<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps/ms?msa=0&amp;msid=205438745984292972946.0004d384e81cba68b206c&amp;ie=UTF8&amp;t=m&amp;ll=52.513681,13.308177&amp;spn=0.002285,0.00456&amp;z=17&amp;output=embed"></iframe>
<br /><small><a target="_blank" title="<?php echo $this->translate("show on a larger map"); ?>" href= "https://maps.google.de/maps/ms?msa=0&amp;msid=205438745984292972946.0004d384e81cba68b206c&amp;ie=UTF8&amp;t=m&amp;ll=52.513681,13.308177&amp;spn=0.002285,0.00456&amp;z=17&amp;source=embed" style="color:#0000FF;text-align:left">Jugendclubring Berlin e.V. Haus der Jugend Charlottenburg</a></small>