<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');

$this->headTitle('League Roster');

/* @var $season \Season\Entity\Season */
$season = $this->season;

$info = $this->translate("Found %no% empty league(s)");
$info = str_replace('%no%', count($this->unassigned), $info);

/* @var $player \User\Entity\User */
$title = sprintf("%s: %s %s",
    $this->translate('Unassigned Leagues'),
    $this->seasonTitle($season),
    $this->translate('League'));
?>

    <h3><?php echo $title;?></h3>

<?php $this->placeholder('noLeague')->captureStart();?>
<?php echo $this->translate("No unassigned leagues found."); ?><br/>
<?php $this->placeholder('noLeague')->captureEnd();?>


<?php $this->placeholder('clean')->captureStart();?>

    <h5><?php echo $this->translate("Season no.") . ' ' . $season->getNumber()?></h5>
    <hr>
<?php echo $info . ': '; ?>
    <ul>
<?php foreach ($this->unassigned as $league) : ?>
        <li><?php echo $this->translate('League no.') . ': ' . $league->getNumber() ?></li>
<?php
endforeach
?>
    </ul>
<?php $this->placeholder('clean')->captureEnd(); ?>


<?php

if (empty($this->unassigned)) {
    echo $this->placeholder('noLeague');
} else {
    echo $this->placeholder('clean');
}

