<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');

$title = $this->translate("Edit Leagues");
$this->headTitle('League');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1><hr/>
<?php $this->placeholder('nothing')->captureStart();?>
    <p><?php echo $this->translate("No league found."); ?></p>
<?php $this->placeholder('nothing')->captureEnd(); ?>

<?php $this->placeholder('actual')->captureStart();?>
<h4><?php echo $this->translate("Season no.") . ' ' . $season->getNumber()?></h4><br/>
<table class="table edit">
    <tr>
        <th><?php echo $this->translate("Id"); ?></th>
        <th><?php echo $this->translate("No"); ?></th>
        <th><?php echo $this->translate("Player"); ?></th>
        <th></th>
    </tr>
    <?php

/* @var $league \Season\Entity\League */
foreach ($this->leagues as $league) : ?>
    <tr style="background-color:<?php
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
      <td><?php echo $league->getId(); ?></td>
      <td><?php echo $league->getNumber();?></td>
      <td><?php echo $league->getNoPlayers();?></td>
      <td class="edit" >
         <a class="button edit" title="<?php echo $this->translate("edit");?>"
            href="<?php echo $this->url('createLeague', array('action' => 'edit', 'id' => $league->getId()));  ?>"></a>
      </td>
    </tr>
<?php
endforeach;
?>
<?php $this->placeholder('actual')->captureEnd(); ?>

<?php

if (!empty($this->leagues)) {
    echo $this->placeholder('actual');
} else {
    echo $this->placeholder('nothing');
}
?>

</table>
<a class="btn" href="<?php echo $this->url('createSeason', array('action' => 'create')); ?>"><?php echo "back" ?></a>
