<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');

$title = $this->translate("Edit New Season's Leagues");
$this->headTitle('League');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<h5><?php echo $this->translate("Season no.") . ' ' . $season->getNumber()?></h5>
<table class="table" style="width:auto">
    <tr>
        <th><?php echo $this->translate("Id"); ?></th>
        <th><?php echo $this->translate("No"); ?></th>
        <th><?php echo $this->translate("Player"); ?></th>
        <th></th>
    </tr>
    <?php

/* @var $league \Season\Entity\League */
foreach ($this->leagues as $league) : ?>
    <tr style="background-color:<?php
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
        <td style="text-align:center"><?php echo $league->getId(); ?></td>
        <td style="text-align:center"><?php echo $league->getNumber();?></td>
        <td style="text-align:center"><?php echo $league->getNoPlayers();?></td>
        <td style="text-align:center" title="<?php echo $this->translate("edit");?>">
            <a href="<?php echo $this->url('createLeague', array('action' => 'edit', 'id' => $league->getId()));  ?>">
                <img src="/images/edit.png">
            </a>
        </td>
    </tr>
<?php
endforeach;
?>
</table>
<a class="btn" href="<?php echo $this->url('createSeason', array('action' => 'create')); ?>"><?php echo "back" ?></a>