<?php if ($this->pageCount > 1): ?>
<div id="myPagination">
    <ul class="large">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
        <li title="<?php echo $this->translate('previous'); ?>">
            <a class="arrows-32 control-left-32" href="<?php echo $this->pagingUrl($this->previous); ?>"></a>
        </li>
    <?php endif; ?>
    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li class="page">
                <a href="<?php echo $this->pagingUrl($page);?>"><?php echo $page; ?></a>
            </li>
        <?php else: ?>
            <li class="page" title="<?php echo $this->translate("Actual Page") . $this->current; ?>">
                <a class="actual" href="#"><?php echo $page; ?></a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
        <li title="<?php echo $this->translate('next'); ?>">
            <a class="arrows-32 control-right-32" href="<?php echo $this->pagingUrl($this->next); ?>"></a>
        </li>
    <?php endif; ?>
    </ul>
</div>
<?php endif; ?>