<?php if ($this->pageCount): ?>
    <div class="matchDayPagination">
        <ul class="nakadePagination nakadePagination-centered">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li title="<?php echo $this->translate('previous'); ?>">
                <a class="arrows-16 control-double-left-16" href="<?php echo $this->pagingUrl($this->previous); ?>">

                </a>
            </li>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li title="<?php echo $this->translate('click'); ?>">
                    <a href="<?php echo $this->pagingUrl($page);?>"><?php echo $page; ?></a>
                </li>
            <?php else: ?>
                <li class="active">
                    <a href="#"><?php echo $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li title="<?php echo $this->translate('next'); ?>">
                <a class="arrows-16 control-double-right-16" href="<?php echo $this->pagingUrl($this->next); ?>"></a>
            </li>
        <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>