<?php
$this->plugin('translate')->setTranslatorTextDomain('Support');

$title = $this->translate('Support Inquiry');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php
    echo $this->translate("If you have a problem, please provide the necessary information."); ?><br/>
<?php echo $this->translate("Your request will be processed as soon as possible."); ?>
</p>
<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();
