<?php
$this->plugin('translate')->setTranslatorTextDomain('Support');
/*  @var $ticket \Support\Entity\SupportRequest
 *  @var $message \Support\Entity\SupportMessage
 */
$this->headTitle('Support');

?>

<?php $this->placeholder('nothing')->captureStart();?>
<h3><?php echo $this->translate('No Ticket found'); ?></h3>
<?php $this->placeholder('nothing')->captureEnd(); ?>

<?php $this->placeholder('ticket')->captureStart();?>
<h3><?php echo $this->translate('Ticket Details'); ?></h3>
<table id="info">
    <?php if (!is_null($ticket->getAssociation())) : ?>
        <tr>
            <td><?php echo $this->translate("League") . ': '; ?></td>
            <td><?php echo $ticket->getAssociation()->getName(); ?></td>
        </tr>
    <?php endif; ?>
    <tr>
        <td><?php echo $this->translate("Subject") . ': '; ?></td>
        <td><?php echo $ticket->getSubject()->getName(); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate("Stage") . ': '; ?></td>
        <td title="<?php echo $this->ticketStageInfo($ticket->getStage()->getId());?>">
            <div class="mail-16 <?php echo $this->ticketStage($ticket->getStage()->getId());?> btnCenter"></div>
        </td>
    </tr>
</table>

<table id="ticket">
    <?php foreach ($ticket->getMessages() as $message) : ?>
        <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
            <td><label><?php echo $message->getAuthor()->getShortName()?></label><label><?php echo $message->getDate()->format('d.m.y H:i'); ?></label>
                <p><?php echo $message->getMessage(); ?></p>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<a class="btn btn-success return" href="<?php echo $this->url('support'); ?>"><?php echo $this->translate("Return"); ?></a>

<?php if ($ticket->getStage()->isNew()) : ?>
    <a class="btn btn-success" href="<?php echo $this->url('support',
        array('action' => 'cancel', 'id' => $ticket->getId())); ?>">
        <?php echo $this->translate("Decline"); ?>
    </a>
<?php endif; ?>

<?php if ($ticket->getStage()->isWaiting()) : ?>
    <a class="btn btn-success actionBtn" href="<?php echo $this->url('support',
        array('action' => 'mail', 'id' => $ticket->getId())); ?>">
        <div class="mail-16 mail-yellow-16"></div><span><?php echo $this->translate("Mail");?></span>
    </a>
<?php endif; ?>

<?php $this->placeholder('tickets')->captureEnd();?>

<div class="widget">
    <?php if (empty($this->ticket)) {
        echo $this->placeholder('nothing');
    } else {
        echo $this->placeholder('tickets');
    }
    ?>
</div>