<?php
$this->plugin('translate')->setTranslatorTextDomain('Support');
/* @var $support \Support\Entity\SupportRequest */
$this->headTitle('Support');

?>

<?php $this->placeholder('nothing')->captureStart();?>
    <h3><?php echo $this->translate('No Tickets found'); ?></h3>
<?php $this->placeholder('nothing')->captureEnd(); ?>

<?php $this->placeholder('tickets')->captureStart();?>
    <h3 style="margin-bottom: 10px;"><?php echo $this->translate('My Support Tickets'); ?></h3>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'moderator'); ?>
    <table class="table profile">
        <tr>
            <th><?php echo $this->translate("ID"); ?></th>
            <th><?php echo $this->translate("League"); ?></th>
            <th><?php echo $this->translate("Subject"); ?></th>
            <th><?php echo $this->translate("Date"); ?></th>
            <th><?php echo $this->translate("Stage"); ?></th>
            <th><?php echo $this->translate("Details"); ?></th>
        </tr>
        <?php foreach ($this->tickets as $support) : ?>
            <tr style="background-color:<?php
            echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
                <td style="text-align: right"><?php echo $support->getId(); ?></td>
                <td><?php echo $support->getAssociation()->getName();?></td>
                <td><?php echo $support->getSubject()->getName(); ?></td>
                <td><?php echo $support->getCreateDate()->format('d.m.y H:i'); ?></td>
                <td>
                    <div class="mail-16 <?php echo $this->ticketStage($support->getStage()->getId());?> btnCenter"></div>
                </td>
                <td>
                    <a class="button" href="<?php echo $this->url('support',
                        array('action' => 'detail', 'id' => $support->getId()))?>">
                        <div class="buttons-16 info-16 btnCenter"></div>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <p><?php echo $this->translate("Total") . ' ' . $this->paginator->getTotalItemCount() . ' ' . $this->translate("Ticket(s)"); ?></p>
<?php $this->placeholder('tickets')->captureEnd();

if (empty($this->tickets)) {
    echo $this->placeholder('nothing');
} else {
    echo $this->placeholder('tickets');
}