<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('User'); 
$title = $this->translate('Registered Users');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<a href="user/add"><?php echo $this->translate("add user"); ?></a>
<table class="table" style="width:auto">
<tr>
    <th><?php echo $this->translate("Sex"); ?></th>
    <th><?php echo $this->translate("Name"); ?></th>
    <th><?php echo $this->translate("Nick"); ?></th>
    <th><?php echo $this->translate("Username"); ?></th>
    <th><?php echo $this->translate("KGS"); ?></th>
    <th><?php echo $this->translate("email"); ?></th>  
    <th><?php echo $this->translate("verified"); ?></th>     
    <th><?php echo $this->translate("active"); ?></th>
    <th><?php echo $this->translate("edit"); ?></th>    
    <th><?php echo $this->translate("access"); ?></th>
    <th><?php echo $this->translate("pwd"); ?></th>
</tr>
<?php 

foreach ($this->users as $user) : ?>
<tr style="background-color:<?php 
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td style="width:1em;text-align:center"><?php echo $this->salutation($user->getSex()); ?></td>
    <td><?php echo $this->escapeHtml($user->getName());?></td>
    <td><?php echo $this->escapeHtml($user->getNickname());?></td>
    <td><?php echo $this->escapeHtml($user->getUsername()); ?></td>
    <td><?php echo $this->escapeHtml($user->getKgs()); ?></td>
    <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
    <td style="width:1em;text-align:center"><?php echo $this->showVerified($user); ?></td>
    <td style="width:1em;text-align:center"><?php echo $this->showActive($user->isActive()); ?></td>
    <td style="text-align:center"><?php echo $this->showEdit($user->getId()); ?></td>
    <td style="text-align:center"><?php echo $this->showTrigger($user);?></td>
    <td style="text-align:center"><?php echo $this->showPwdReset($user->getId()); ?></td>
</tr>
<?php endforeach; ?>
</table>
