<?php
$this->plugin('translate')->setTranslatorTextDomain('User');

$title = $this->translate('Password Reset');
$this->headTitle($title);
?>
<h1><?php echo $this->translate("Reset Password?"); ?></h1>

<?php $this->placeholder('nothing')->captureStart();?>
    <p><?php echo $this->translate("User not found."); ?></p>
    <a class="btn btn-success" href="<?php echo $this->url('user')?>"><?php echo $this->translate("Return"); ?></a>
<?php $this->placeholder('nothing')->captureEnd(); ?>

<?php $this->placeholder('actual')->captureStart();?>
<p>
<?php echo str_replace("%NAME%",
    $this->user->getName(),
    $this->translate("This will generate a new password for %NAME%.")); ?><br/>
<?php echo str_replace("%EMAIL%",
    $this->user->getEmail(),
    $this->translate("The new password is sent to %EMAIL%.")); ?>
</p>
<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();
?>
<?php $this->placeholder('actual')->captureEnd();?>

<?php
if (!empty($this->user)) {
echo $this->placeholder('actual');
} else {
echo $this->placeholder('nothing');
}
