<?php
$this->plugin('translate')->setTranslatorTextDomain('User'); 

$title = $this->translate('Account Activation');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p style="margin-top:1em;">
<?php 
   
    $success = $this->translate("Thank you for your activation.") . "\n" .
               $this->translate("You can logIn using your credentials.");
    
    $failure = $this->translate("Activation failed.") . "\n" .
               $this->translate("Probably your credentials are expired.");
               
    $message = $this->isActivated? nl2br($success) : nl2br($failure);
    echo $message;?>
</p>
