<?php
$this->plugin('translate')->setTranslatorTextDomain('League'); 

$title = $this->translate('edit match day');
$this->headTitle('League');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table" style="width:auto">
<tr>
    <th><?php echo $this->translate("Matchday"); ?></th>
    <th><?php echo $this->translate("League"); ?></th>
    <th><?php echo $this->translate("Black"); ?></th>
    <th><?php echo $this->translate("White"); ?></th>
    <th style="text-align:center"><?php echo $this->translate("Date"); ?></th>     
    <th><?php echo $this->translate("edit"); ?></th>  
</tr>
<?php 


foreach ($this->matches as $match) : ?>
<tr style="background-color:<?php 
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td style="text-align:center"><?php echo $match->getMatchday(); ?></td>
    <td style="text-align:center"><?php echo $match->getLeague()->getNumber(); ?></td>
    <td><?php echo $this->escapeHtml($match->getBlack()->getCompleteName());?></td>
    <td><?php echo $this->escapeHtml($match->getWhite()->getCompleteName());?></td>
    <td style="text-align:center"><?php echo $match->getDate()->format('D, d.m.Y H:i');?></td>
    <td style="text-align:center"><?php echo $this->showEdit($match->getId(), "matchday");?></td>
</tr>
<?php endforeach; ?>
</table>