<?php
$this->plugin('translate')->setTranslatorTextDomain('Certificate');
$this->headTitle('Stats');
/* @var $player \Stats\Entity\PlayerStats */
/* @var $tournament \Season\Entity\League */
?>


<?php $this->placeholder('noSeason')->captureStart();?>
   <h1><?php echo $this->translate("Certificate of Excellence"); ?></h1>
   <h3>Awarded To</h3>
    <h2>Heinz Pooh</h2>

    For Winning the 2. Division

    Of the 4. Nakade League 2015

    //in the Game of Go

    13th November 2015
    Dr. H. Maerz
<?php $this->placeholder('noSeason')->captureEnd();?>


<?php $this->placeholder('actual')->captureStart();?>
<div class="widget">

</div>
<?php $this->placeholder('actual')->captureEnd(); ?>


<?php

 if (true) {
     echo $this->placeholder('noSeason');
 } else {
     echo $this->placeholder('actual');
 }

