<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('League'); 
$title = $this->translate('Season Overview');
$this->headTitle('Overview');
?>

<h3><?php echo $this->escapeHtml( $title); ?></h3>

<?php $this->placeholder('noseason')->captureStart();?>
  <a href="/newseason/add" title="<?php echo $this->translate("create new season");?>">
      <?php echo $this->translate("create new season"); ?>
  </a>
<?php $this->placeholder('noseason')->captureEnd();?>


<?php $this->placeholder('actual')->captureStart();?>
<h5><?php echo $this->translate("actual season") . ':'?>
    <?php echo $this->seasontitle($this->actual); ?></h5>
<ul> 
<?php foreach ($this->status as $key=> $value) : ?>
         <li><?php echo $key .': '.$value; ?></li> 
 <?php endforeach; ?>                            
</ul>
                           
<?php $this->placeholder('actual')->captureEnd(); ?> 
                         
 <?php $this->placeholder('newseason')->captureStart();?>                          
 <h5><?php echo $this->translate("next season") . ':'?>
    <?php echo $this->seasontitle($this->new);      
     ?></h5>
<ul> 
<?php foreach ($this->newstatus as $key=> $value) : ?>
         <li><?php echo $key .': '.$value; ?></li> 
 <?php endforeach; ?>                            
</ul>
 
 - empfehlung: add league | add players | move start date<br>

<?php $this->placeholder('newseason')->captureEnd(); 

 if($this->status!=null)
      echo $this->placeholder('actual');
 else echo $this->placeholder('noseason');
 
 if($this->newstatus!=null)
    echo $this->placeholder('newseason');
 else echo $this->placeholder('noseason');
?>
