<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');
$head = 'Remove Match Days';
$this->headTitle($head);
/* @var $matchDay \Season\Entity\MatchDay */
?>

<?php $this->placeholder('noData')->captureStart();?>
<h3><?php echo $this->translate('No match days found')?></h3>
<?php $this->placeholder('noData')->captureEnd(); ?>

<?php $this->placeholder('data')->captureStart();?>
<h1><?php echo $this->translate("Remove all Match Days?"); ?></h1>
<p><?php echo $this->translate("These are all match days of the next season.");?><br/>
    <?php echo $this->translate("If deleted, you will have to renew the match day configuration.");?>
</p>
<table class="table" style="width: auto; margin-top: 0.5em;text-align: center;">
<tr>
    <th><?php echo $this->translate("round"); ?></th>
    <th><?php echo $this->translate("date"); ?></th>
</tr>

<?php foreach ($this->matchDays as $matchDay) : ?>
<tr style="background-color:<?php
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $matchDay->getMatchDay();?></td>
    <td><?php echo $matchDay->getDate()->format('D, d.m.Y H:i');?></td>
</tr>
<?php
endforeach; ?>
</table>

<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();
?>

<?php $this->placeholder('data')->captureEnd();


  if (count($this->matchDays)>0) {
      echo $this->placeholder('data');
  } else {
      echo $this->placeholder('noData');
  }
