<?php
$head = 'Match Days';
$this->headTitle($head);
/* @var $matchDay \Season\Entity\MatchDay */
?>

<h1><?php echo $this->translate("Match Days of the next Season"); ?></h1>
<?php $this->placeholder('noData')->captureStart();?>
<h3><?php echo $this->translate('No match days found')?></h3>
<?php $this->placeholder('noData')->captureEnd(); ?>

<?php $this->placeholder('data')->captureStart();?>
<table class="table" style="margin-top: 0.5em;">
<tr>
    <th><?php echo $this->translate("match day"); ?></th>
    <th><?php echo $this->translate("date"); ?></th>
    <th><?php echo $this->translate("edit"); ?></th>
</tr>

<?php foreach ($this->matchDays as $matchDay) : ?>
<tr style="background-color:<?php
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $matchDay->getMatchDay();?></td>
    <td><?php echo $matchDay->getDate()->format('d.m.Y H:i');?></td>
    <td><?php echo $this->showEdit($matchDay->getId(), "configMatchDay");?></td>
</tr>
<?php
endforeach; ?>
</table>
<?php $this->placeholder('data')->captureEnd();


  if (is_null($this->matchDays)) {
      echo $this->placeholder('noData');
  } else {
      echo $this->placeholder('data');
  }
