<?php
$this->plugin('translate')->setTranslatorTextDomain('Season');
$head = 'Match Days';
$this->headTitle($head);
/* @var $matchDay \Season\Entity\MatchDay */
?>

<?php $this->placeholder('noData')->captureStart();?>
<h3><?php echo $this->translate('No match days found.')?></h3>
<?php $this->placeholder('noData')->captureEnd(); ?>

<?php $this->placeholder('data')->captureStart();?>
<h1><?php echo $this->translate("Match Days of the Next Season"); ?></h1>
<table class="table edit">
<tr>
    <th><?php echo $this->translate("round"); ?></th>
    <th><?php echo $this->translate("date"); ?></th>
    <th><?php echo $this->translate("edit"); ?></th>
</tr>

<?php foreach ($this->matchDays as $matchDay) : ?>
<tr style="background-color:<?php
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $matchDay->getMatchDay();?></td>
    <td><?php echo $matchDay->getDate()->format('D, d.m.Y H:i');?></td>
    <td class="edit">
      <a class="button edit"  title="<?php echo $this->translate("edit");?>"
         href="<?php echo $this->url('configMatchDay', array('action' => 'edit', 'id' => $matchDay->getId()));  ?>"></a>
    </td>
</tr>
<?php
endforeach; ?>
</table>
<a class="btn" href="<?php echo $this->url('createSeason', array('action' => 'create')); ?>"><?php echo $this->translate("Return"); ?></a>
<?php $this->placeholder('data')->captureEnd();


  if (!empty($this->matchDays)) {
      echo $this->placeholder('data');
  } else {
      echo $this->placeholder('noData');
  }
