<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('League'); 

$headline = $this->translate("Last Season") . $this->number;
$this->headTitle($headline);

?>
<h3><?php echo $this->escapeHtml($headline); ?></h3>

<table style="width:15em;margin-top: 0.5em;">
<tr>
    <td><?php echo $this->translate("Leagues:");?></td>
    <td><?php echo $this->noLeagues;?></td>
</tr>
<tr>
    <td><?php echo $this->translate("Players:");?></td>
    <td><?php echo $this->noPlayers;?></td>
</tr>
<tr>
    <td><?php echo $this->translate("Matches:");?></td>
    <td><?php echo $this->openGames;?></td>
</tr>
<tr>
    <td><?php echo $this->translate("Champion:");?></td>
    <td><?php foreach($this->winner as $champion) 
                  echo $this->player($champion->getPlayer());
    ?></td>
</tr>
</table>


     
        

