<?php
$this->plugin('translate')->setTranslatorTextDomain('Message'); 
$this->headTitle("Messages");
?>
<?php $this->placeholder('nothing')->captureStart();?>
<h3><?php echo $this->translate('No messages found')?></h3>
<?php $this->placeholder('nothing')->captureEnd(); ?>


<?php $this->placeholder('messages')->captureStart();?>
<h3><?php //echo $this->escapeHtml($this->title); ?></h3>

<table id="messages" class="table">
    <tr>
        <th><?php echo $this->translate('Subject');?></th>
        <th class="read"><img alt="mail read" src="/images/glasses.png"></th>
        <th><?php echo $this->translate('from')?></th>
        <th><?php echo $this->translate('Date')?></th>
    </tr>
 <?php foreach ($this->messages as $message) : ?>
    <tr class="message" style="background-color:<?php echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
        <td class="subject"><a href="message/show/<?php echo $message->getId() ?>"><?php echo $message->getSubject() ?></a></td>
        <td class="read"><?php if($message->getReadDate())?><img alt="mail read" src="/images/greenball.png"></td>
        <td><?php echo $message->getSender()->getShortName();?></td>
        <td><?php echo $message->getSendDate()->format('d.m.y H:i');?></td>
    </tr>
<?php endforeach; ?>
</table>


<?php $this->placeholder('messages')->captureEnd(); 

  if($this->messages!=null) {
      echo $this->placeholder('messages');
      //echo $this->messageWidget;
  }    
  else echo $this->placeholder('nothing');        
  
  
?>
