<?php
$this->plugin('translate')->setTranslatorTextDomain('Message');
$this->headTitle("Messages");
?>

<h3><?php echo $this->translate("Messages - Inbox"); ?></h3>
<div id="msgAction">
    <form action="<?php echo $this->url('message/new'); ?>">
        <button title="<?php
        echo $this->translate('send a new message');?>" type="submit"><?php
            echo $this->translate('new Message');?>
        </button>
    </form>
    <form action="<?php echo $this->url('message/sent'); ?>">
        <button title="<?php
        echo $this->translate('go to sent messages');?>" type="submit"><?php
            echo $this->translate('Sent Box');?>
        </button>
    </form>
</div>

<?php $this->placeholder('nothing')->captureStart();?>
<h3><?php echo $this->translate('No messages found')?></h3>

<?php $this->placeholder('nothing')->captureEnd(); ?>


<?php $this->placeholder('messages')->captureStart();?>

<table id="messages" class="table">
    <tr>
        <th><?php echo $this->translate('ID');?></th>
        <th><?php echo $this->translate('Subject');?></th>
        <th><?php echo $this->translate('from')?></th>
        <th><?php echo $this->translate('Date')?></th>
        <th></th>
    </tr>
 <?php foreach ($this->messages as $message) : ?>
    <tr class="message" style="background-color:<?php echo $this->cycle(array("#F0F0F0","transparent"))->next()?>;
        <?php if ($message->isNew()) {
            echo "font-weight:bold;";
}?>
        ">
        <td style="text-align:right;"><?php echo $message->getId(); ?></td>
        <td class="subject"><a href="<?php
            echo $this->url('message/show') . '/' . $message->getId(); ?>"><?php echo $message->getSubject() ?></a>
        </td>
        <td><?php echo $message->getSender()->getShortName();?></td>
        <td><?php echo $message->getSendDate()->format('d.m.y H:i');?></td>
        <td><a href="<?php
            echo $this->url('message/delete'). '/' . $message->getId(); ?>"
               title="<?php echo $this->translate('delete')?>">
               <img style="height:16px;width=16px;margin-left:10px;vertical-align: middle" src="/images/trash.png">
            </a>
        </td>
    </tr>
<?php endforeach; ?>
</table>


<?php $this->placeholder('messages')->captureEnd();

  if (0==count($this->messages)) {
      echo $this->placeholder('nothing');

  } else {
      echo $this->placeholder('messages');
  }



