<?php
$this->plugin('translate')->setTranslatorTextDomain('Message');
$this->headTitle("Messages");
?>

<h3><?php echo $this->translate("Messages - Sent"); ?></h3>


<?php $this->placeholder('nothing')->captureStart();?>
    <h3><?php echo $this->translate('No messages found')?></h3>
<?php $this->placeholder('nothing')->captureEnd(); ?>


<?php $this->placeholder('messages')->captureStart();?>

    <table id="messages" class="table">
        <tr>
            <th><?php echo $this->translate('ID');?></th>
            <th><?php echo $this->translate('Subject');?></th>
            <th class="read" title="<?php
                echo $this->translate('reading state');?>"><img alt="mail read" src="/images/glasses.png">
            </th>
            <th><?php echo $this->translate('to')?></th>
            <th><?php echo $this->translate('Date')?></th>
        </tr>
        <?php foreach ($this->messages as $message) : ?>
            <tr class="message" style="background-color:<?php
                echo $this->cycle(array("#F0F0F0","transparent"))->next()?>; ">
                <td style="text-align:right;"><?php echo $message->getId(); ?></td>
                <td class="subject"><a href="<?php
                    echo $this->url('message',array('action' => 'show', 'id' => $message->getId())); ?>">
                    <?php echo $message->getSubject() ?>
                    </a>
                </td>
                <td class="read"><?php if ($message->isNew()) :?>
                        <img alt="unread" title="<?php echo $this->translate('unread');?>" src="/images/redball.png">
                        <?php else: ?>
                        <img alt="read" title="<?php echo $this->translate('read');?>" src="/images/greenball.png">
                        <?php endif; ?>
                </td>
                <td><?php echo $message->getReceiver()->getShortName();?></td>
                <td><?php echo $message->getSendDate()->format('d.m.y H:i');?></td>
            </tr>
        <?php endforeach; ?>
    </table>


<?php $this->placeholder('messages')->captureEnd();

if (0==count($this->messages)) {
    echo $this->placeholder('nothing');

} else {
    echo $this->placeholder('messages');
}




