<?php
$this->plugin('translate')->setTranslatorTextDomain('Message');
$this->headTitle("Messages");
?>

    <h3><?php echo $this->translate("Messages - Sent"); ?></h3>

<?php $this->placeholder('nothing')->captureStart();?>
    <h3><?php echo $this->translate('No messages found')?></h3>
<?php $this->placeholder('nothing')->captureEnd(); ?>


<?php $this->placeholder('messages')->captureStart();?>


    <div id="msgAction">
        <a href="<?php echo $this->url('message'); ?>"><?php echo $this->translate('Inbox');?></a>
    </div>
    <table id="messages" class="table">
        <tr>
            <th><?php echo $this->translate('Subject');?></th>
            <th class="read" title="<?php echo $this->translate('reading state');?>"><img alt="mail read" src="/images/glasses.png"></th>
            <th><?php echo $this->translate('to')?></th>
            <th><?php echo $this->translate('Date')?></th>
        </tr>
        <?php foreach ($this->messages as $message) : ?>
            <tr class="message" style="background-color:<?php echo $this->cycle(array("#F0F0F0","transparent"))->next()?>;
            <?php if ($message->isNew()) {
                echo "font-weight:bold;";
            }?>
                ">
                <td class="subject"><a href="<?php echo $this->url('message/show') . '/' . $message->getId(); ?>"><?php echo $message->getSubject() ?></a></td>
                <td class="read" title="<?php echo $this->translate('message was read');?>"><?php if ($message->isRead()) :?>
                        <img alt="mail read" src="/images/greenball.png">

                    <?php
                    endif;
                    ?>
                </td>
                <td><?php echo $message->getReceiver()->getShortName();?></td>
                <td><?php echo $message->getSendDate()->format('d.m.y H:i');?></td>
            </tr>
        <?php endforeach; ?>
    </table>


<?php $this->placeholder('messages')->captureEnd();

if (is_null($this->messages)) {
    echo $this->placeholder('nothing');

} else {
    echo $this->placeholder('messages');
}




