<?php
$this->plugin('translate')->setTranslatorTextDomain('Message');
$this->headTitle("Messages");
?>
<?php $this->placeholder('nothing')->captureStart();?>
<h3><?php echo $this->translate('No messages found')?></h3>
<?php $this->placeholder('nothing')->captureEnd(); ?>


<?php $this->placeholder('messages')->captureStart();?>
<h3><?php //echo $this->escapeHtml($this->title); ?></h3>

<div id="msgAction">
    <form action="<?php echo $this->url('message'); ?>"><button type="submit"><?php echo $this->translate('mailbox');?></button></form>
    <form action="<?php echo $this->url('message/archive'); ?>"><button ><?php echo $this->translate('archive');?></button></form>
</div>
<table id="messages" class="table">
    <tr>
        <th><?php echo $this->translate('Subject');?></th>
        <th class="read"><img alt="mail read" src="/images/glasses.png"></th>
        <th><?php echo $this->translate('to')?></th>
        <th><?php echo $this->translate('Date')?></th>
    </tr>
 <?php foreach ($this->messages as $message) : ?>
    <tr class="message" style="background-color:<?php echo $this->cycle(array("#F0F0F0","transparent"))->next()?>;
        <?php if ($message->isNew()) {
            echo "font-weight:bold;";
        }?>
        ">
        <td class="subject"><a href="message/show/<?php echo $message->getId() ?>"><?php echo $message->getSubject() ?></a></td>
        <td class="read"><?php if ($message->isRead()) :?>
            <img alt="mail read" src="/images/greenball.png">

<?php
endif;
?>
        </td>
        <td><?php echo $message->getReceiver()->getShortName();?></td>
        <td><?php echo $message->getSendDate()->format('d.m.y H:i');?></td>
    </tr>
<?php endforeach; ?>
</table>


<?php $this->placeholder('messages')->captureEnd();

  if (is_null($this->messages)) {
      echo $this->placeholder('nothing');

  } else {
      echo $this->placeholder('messages');
  }



