<?php
$this->plugin('translate')->setTranslatorTextDomain('Message');
$this->headTitle("Messages");
?>

<?php $this->placeholder('nothing')->captureStart();?>
    <h3><?php echo $this->translate('No messages found')?></h3>
<?php $this->placeholder('nothing')->captureEnd(); ?>

<?php $this->placeholder('messages')->captureStart();?>

<div id="msgAction">
<form action="<?php echo $this->url('message'); ?>"><button type="submit"><?php echo $this->translate('back');?></button></form>
<form action="<?php echo $this->url('message/reply', array('id' => $this->replyId)); ?>"><button type="submit"><?php echo $this->translate('reply');?></button></form>
<form action="<?php echo $this->url('message'); ?>"><button ><?php echo $this->translate('archive');?></button></form>
<form action="<?php echo $this->url('message'); ?>"><button><?php echo $this->translate('delete');?></button></form>
</div>

<?php foreach ($this->messages as $message) : ?>
<table id="message">
    <tr>
        <th>
            <div class="msghead">
                <div class="container">
                    <div><label><?php echo $this->translate('from');?>:</label><?php echo $message->getSender()->getShortName(); ?></div>
                    <div><label><?php echo $this->translate('subject');?>:</label><?php echo $message->getSubject();?></div>
                </div>
                <div class="container right">
                    <div><label><?php echo $this->translate('send');?>:</label><?php echo $message->getSendDate()->format('d.m.Y H:i');?></div>
    <?php if (!is_null($message->getReadDate())): ?>
                    <div><label><?php echo $this->translate('read');?>:</label>
                        <?php  echo $message->getReadDate()->format('d.m.Y H:i'); ?>
                    </div>
<?php
endif;
    ?>
                </div>
            <div>
        </th>
    </tr>
    <tr class="message">
        <td><?php echo $message->getMessage(); ?></td>
    </tr>
</table>
<?php endforeach; ?>
<?php $this->placeholder('messages')->captureEnd();

if (is_null($this->messages)) {
    echo $this->placeholder('nothing');
}
else {
    echo $this->placeholder('messages');
}