<?php
$this->plugin('translate')->setTranslatorTextDomain('Stats');
$this->headTitle('Stats');
/* @var $stats \Stats\Entity\MatchStats */
?>

<h3><?php echo $title;?></h3>



<?php $this->placeholder('noSeason')->captureStart();?>
   <?php echo $this->translate("No matches found."); ?>
<?php $this->placeholder('noSeason')->captureEnd();?>


<?php $this->placeholder('actual')->captureStart();?>

    <div id="matchStatsContainer" style="display:inline-block;width:310px; height:300px;"></div>
    <div id="winStatsContainer" style="display:inline-block;min-width: 310px; height: 300px; max-width: 410px;"></div>
    <div id="defeatStatsContainer" style="display:inline-block;min-width: 310px; height: 300px; max-width: 410px;"></div>
    <script>

        $(function () {

        var total = <?php echo $stats->getPlayed()?>;
        var defeats =  <?php echo $stats->getDefeats()?>;
        var wins =  <?php echo $stats->getWins()?>;
        var black =   '<?php echo $this->translate('Black')?>';
        var white =   '<?php echo $this->translate('White')?>';
        var matchTitle =   total + ' <?php echo $this->translate('Matches')?>';
        var winTitle =  wins + ' <?php echo $this->translate('Wins')?>';
        var defeatTitle =  defeats + ' <?php echo $this->translate('Defeats')?>';
        var matchDataName =  '<?php echo $this->translate('Match Share')?>';
        var colorDataName =  '<?php echo $this->translate('Total Share')?>';
        var SeriesName =  '<?php echo $this->translate('Share')?>';
        var close =  '<?php echo $this->translate('Close')?>';
        var resign =  '<?php echo $this->translate('Resigns')?>';
        var onTime =  '<?php echo $this->translate('On Time')?>';
        var forfeit =  '<?php echo $this->translate('Forfeit')?>';


        var colors = Highcharts.getOptions().colors,
            categories = [
                '<?php echo $this->translate('Wins')?>',
                '<?php echo $this->translate('Defeats')?>',
                '<?php echo $this->translate('Draws')?>'
            ],
            data = [{
                y: wins,
                color: colors[0],
                drilldown: {
                    name: 'Wins',
                    categories: [black, white],
                    data: [<?php echo $stats->getWinOnBlack()?>, <?php echo $stats->getWinOnWhite()?>],
                    color: colors[0]
                }
            }, {
                y: defeats,
                color: colors[1],
                drilldown: {
                    name: 'Defeats',
                    categories: [black, white],
                    data: [<?php echo $stats->getDefeatOnBlack()?>, <?php echo $stats->getDefeatOnWhite()?>],
                    color: colors[1]
                }
            }, {
                y: <?php echo $stats->getDraws()?>,
                color: colors[2],
                drilldown: {
                    name: 'Draws',
                    categories: [black, white],
                    data: [<?php echo $stats->getDrawOnBlack()?>, <?php echo $stats->getDrawOnWhite()?>],
                    color: colors[2]
                }
            } ],
            matchData = [],
            colorData = [],
            i,
            j,
            dataLen = data.length,
            drillDataLen,
            brightness;


        // Build the data arrays
        for (i = 0; i < dataLen; i += 1) {

            // add match data
            matchData.push({
                name: categories[i],
                y: data[i].y,
                color: data[i].color
            });

            // add version data
            drillDataLen = data[i].drilldown.data.length;
            for (j = 0; j < drillDataLen; j += 1) {
                brightness = 0.2 - (j / drillDataLen) / 5;
                colorData.push({
                    name: data[i].drilldown.categories[j],
                    y: data[i].drilldown.data[j],
                    color: Highcharts.Color(data[i].color).brighten(brightness).get()
                });
            }
        }

        // Create the chart
        $('#matchStatsContainer').highcharts({
            chart: {
                type: 'pie',
                marginTop: 50

            },
            credits: {
                enabled: false
            },
            title: {
               // floating: true,
                y: 40,
                text: matchTitle
            },
            plotOptions: {
                pie: {
                    shadow: false,
                    center: ['50%', '50%']
                }
            },

            series: [{
                data: matchData,
                name: matchDataName,
                size: '70%',
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                },
                dataLabels: {
                    formatter: function () {
                        return this.y > 1 ? this.y + ' ' + this.point.name: null;
                    },
                    style: {
                        fontWeight: 'bold',
                        color: 'white',
                        textShadow: '0px 1px 2px black'
                    },
                    distance: -45
                }
            }, {
                data: colorData,
                name: colorDataName,
                size: '80%',
                innerSize: '70%',
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                },
                dataLabels: {
                    distance: 5,
                    formatter: function () {
                        // display only if larger than 1
                        return this.y > 1 ? '<b>' + this.point.name + ':</b> ' + this.y : null;
                    }
                }
            }]
        });

        //win container
        $('#winStatsContainer').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: 0,
                plotShadow: false
            },
            credits: {
                enabled: false
            },
            title: {
                text: winTitle,
                align: 'center',
                verticalAlign: 'middle',
                y: 50
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    dataLabels: {
                        enabled: true,
                        distance: -35,
                        style: {
                            fontWeight: 'bold',
                            color: 'white',
                            textShadow: '0px 1px 2px black'
                        }
                    },
                    startAngle: -90,
                    endAngle: 90,
                    center: ['50%', '75%']
                }
            },
            series: [{
                type: 'pie',
                name: SeriesName,
                innerSize: '55%',
                data: [
                    [close, <?php echo $stats->getCloseWins()?>],
                    [resign, <?php echo $stats->getHighWins()?>]
                ],
                dataLabels: {
                    formatter: function () {
                        return this.y > 0 ? this.y + ' ' + this.point.name: null;
                    },
                    style: {
                        fontWeight: 'bold',
                        color: 'white',
                        textShadow: '0px 1px 2px black'
                    },
                    distance: -35
                }
            }]
        });

        //defeat container
        $('#defeatStatsContainer').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: 0,
                plotShadow: false
            },
            credits: {
                enabled: false
            },
            title: {
                text: defeatTitle,
                align: 'center',
                verticalAlign: 'middle',
                y: 50
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    dataLabels: {
                        enabled: true,
                        distance: -35,
                        style: {
                            fontWeight: 'bold',
                            color: 'white',
                            textShadow: '0px 1px 2px black'
                        }
                    },
                    startAngle: -90,
                    endAngle: 90,
                    center: ['50%', '75%']
                }
            },
            series: [{
                type: 'pie',
                name: SeriesName,
                innerSize: '55%',
                data: [
                    [close, <?php echo $stats->getCloseDefeats()?>],
                    [resign, <?php echo $stats->getLostByResign()?>],
                    [onTime, <?php echo $stats->getLostOnTime()?>],
                    [forfeit, <?php echo $stats->getLostByForfeit()?>]
                ],
                dataLabels: {
                    formatter: function () {
                        return this.y > 0 ? this.y + ' ' + this.point.name: null;
                    },
                    style: {
                        fontWeight: 'bold',
                        color: 'white',
                        textShadow: '0px 1px 2px black'
                    },
                    distance: -35
                }
            }]
        });
        });

    </script>


<?php $this->placeholder('actual')->captureEnd(); ?>


<?php

 if (empty($this->stats) || $stats->getPlayed() == 0) {
     echo $this->placeholder('noSeason');
 } else {
     echo $this->placeholder('actual');
 }

