<?php
$this->plugin('translate')->setTranslatorTextDomain('Stats');
$this->headTitle('Stats');
/* @var $player \Stats\Entity\PlayerStats */
?>

<h3><?php //echo $title;?></h3>



<?php $this->placeholder('noSeason')->captureStart();?>
   <?php echo $this->translate("No matches found."); ?>
<?php $this->placeholder('noSeason')->captureEnd();?>


<?php $this->placeholder('actual')->captureStart();?>

<ul class="playerStats">
    <li><?php echo $this->translate('Tournaments') .': '. $player->getNoTournaments(); ?><a
            href="<?php echo $this->url('stats', array('action' => 'tournament'));?>"><div
                class="buttons-16 info-16"></div>
        </a>
    </li>
    <?php if ($player->getNoGames() > 0): ?>
    <li><?php echo $this->translate('Played') .': '. $player->getNoGames(); ?></li>
    <?php endif; ?>
    <?php if ($player->getNoWin() > 0): ?>
    <li><?php echo $this->translate('Win') .': '. $player->getNoWin(); ?></li>
    <?php endif; ?>
    <?php if ($player->getNoDraw() > 0): ?>
    <li><?php echo $this->translate('Draw') .': '. $player->getNoDraw(); ?></li>
    <?php endif; ?>
    <?php if ($player->getNoLoss() > 0): ?>
    <li><?php echo $this->translate('Defeat') .': '. $player->getNoLoss(); ?></li>
    <?php endif; ?>
    <?php if ($player->getNoConsecutiveWins() > 1): ?>
    <li><?php echo $this->translate('Consecutive wins') .': '. $player->getNoConsecutiveWins(); ?></li>
    <?php endif; ?>
</ul>

<ul class="achievement">
    <?php if ($player->getChampion()->getNoGold() > 0): ?>
    <li><?php foreach ($player->getChampion()->getGold() as $tournament) :?>
        <a  href="<?php  ?>"><div class="nakade-16 crown-gold-16"></div></a>
        <?php endforeach;?>
    </li>
    <?php endif; ?>
    <?php if ($player->getChampion()->getNoSilver() > 0): ?>
    <li><?php foreach ($player->getChampion()->getSilver() as $tournament) :?>
        <a  href="<?php  ?>"><div class="nakade-16 crown-silver-16"></div></a>
        <?php endforeach;?>
    </li>
    <?php endif; ?>
    <?php if ($player->getChampion()->getNoBronze() > 0): ?>
    <li><?php foreach ($player->getChampion()->getBronze() as $tournament) :?>
            <a  href="<?php  ?>"><div class="nakade-16 crown-bronze-16"></div></a>
        <?php endforeach;?>
    <?php endif; ?>

    <?php if ($player->getCup()->getNoGold() > 0): ?>
    <li><?php foreach ($player->getCup()->getGold() as $tournament) :?>
            <a  href="<?php  ?>"><div class="nakade-16 cup-gold-16"></div></a>
        <?php endforeach;?>
    </li>
    <?php endif; ?>
    <?php if ($player->getCup()->getNoSilver() > 0): ?>
        <li><?php foreach ($player->getCup()->getSilver() as $tournament) :?>
                <a  href="<?php  ?>"><div class="nakade-16 cup-silver-16"></div></a>
            <?php endforeach;?>
        </li>
    <?php endif; ?>
    <?php if ($player->getCup()->getNoBronze() > 0): ?>
    <li><?php foreach ($player->getCup()->getBronze() as $tournament) :?>
            <a  href="<?php  ?>"><div class="nakade-16 cup-bronze-16"></div></a>
        <?php endforeach;?>
    <?php endif; ?>

    <?php if ($player->getMedal()->getNoGold() > 0): ?>
    <li><?php foreach ($player->getMedal()->getGold() as $tournament) :?>
            <a  href="<?php  ?>"><div class="nakade-16 medal-gold-16"></div></a>
        <?php endforeach;?>
    </li>
    <?php endif; ?>
    <?php if ($player->getMedal()->getNoSilver() > 0): ?>
        <li><?php foreach ($player->getMedal()->getSilver() as $tournament) :?>
                <a  href="<?php  ?>"><div class="nakade-16 medal-silver-16"></div></a>
            <?php endforeach;?>
        </li>
    <?php endif; ?>
    <?php if ($player->getMedal()->getNoBronze() > 0): ?>
    <li><?php foreach ($player->getMedal()->getBronze() as $tournament) :?>
            <a  href="<?php  ?>"><div class="nakade-16 medal-bronze-16"></div></a>
        <?php endforeach;?>
    <?php endif; ?>

</ul>

<?php $this->placeholder('actual')->captureEnd(); ?>


<?php

 if ($this->player->getNoTournaments() == 0) {
     echo $this->placeholder('noSeason');
 } else {
     echo $this->placeholder('actual');
 }

