<?php
$this->plugin('translate')->setTranslatorTextDomain('Stats');
$this->headTitle('Stats');
/* @var $tournament \Stats\Entity\Tournament */
?>

<h3><?php echo $title;?></h3>



<?php $this->placeholder('noSeason')->captureStart();?>
   <?php echo $this->translate("No matches found."); ?>
<?php $this->placeholder('noSeason')->captureEnd();?>


<?php $this->placeholder('actual')->captureStart();?>

tournaments : <?php echo count($this->tournaments); ?>
pos : <?php echo $this->position; ?>

<?php $this->placeholder('actual')->captureEnd(); ?>


<?php

 if (count($this->tournaments) == 0) {
     echo $this->placeholder('noSeason');
 } else {
     echo $this->placeholder('actual');
 }

