<?php
$this->plugin('translate')->setTranslatorTextDomain('User');
$title = $this->translate('Reset Password');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p  class="userMsg"><?php echo $this->translate("Please enter your registered email."); ?><br/>
<?php echo $this->translate("Your new credentials will be sent to you."); ?>
</p>

<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();
