<?php
$this->plugin('translate')->setTranslatorTextDomain('User');
$title = $this->translate('Registration');
$this->headTitle($title);
?>
<div class="widget">
<h1><?php echo $this->translate('Go Players Wanted'); ?></h1>
<p style="text-align:justify">
<?php echo $this->translate("For our closed beta, we are looking for passionate adult players.") . ' ' .
 $this->translate("You have a rank from 1d-15k, love the game and challenges on equal terms.") . ' ' .
 $this->translate("Despite your restricted time, you can make it on Tuesday every 2-3 weeks frequently.") . ' ' .
 $this->translate("Due to our match time at 6:30 pm (CET), you should resident in the EC."). ' ' ; ?>
</p>
<p style="letter-spacing:1px; text-transform: uppercase"><?php echo $this->translate("You received a coupon code!"); ?></p>
    <a style="margin-top:10px" class='btn' href="<?php echo $this->url('register');?>">
        <?php echo $this->translate('Register NOW!');?>
    </a>
</div>
