<?php
$this->plugin('translate')->setTranslatorTextDomain('User');
$title = $this->translate('Registration');
$this->headTitle($title);
?>
<div class="widget">
<h1><?php echo $this->translate('Closed Beta Registration'); ?></h1>
<p>
<?php echo $this->translate("We are happy to announce having achieved closed beta."); ?><br/>
<?php echo $this->translate("This Adult Go players from the EC We are happy to announce having achieved closed beta."); ?><br/>
<?php echo $this->translate("For invited Go players only."); ?><br/>
<?php echo $this->translate("You need a coupon code to register."); ?><br/>
<?php echo $this->translate("For league matches, a KGS account is mandatory."); ?>
</p>
    <a class='btn' href="<?php
    $this->url('register', array('action' => 'show'));?>"><?php echo $this->translate('Register NOW!');?></a>
</div>
