<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('User');
$title = $this->translate('Confirming Failed');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p style="font-size:larger;margin: 10px 0;">
    <?php echo $this->translate("The validity of the used link is expired."); ?><br/>
    <?php echo $this->translate("Find more details in your mail."); ?>
</p>
