<?php
$this->plugin('translate')->setTranslatorTextDomain('Support');
/*  @var $ticket \Support\Entity\Feature
 *  @var $message \Support\Entity\SupportMessage
 */
$this->headTitle('Support');

?>

<?php $this->placeholder('nothing')->captureStart();?>
<h3><?php echo $this->translate('No Ticket found'); ?></h3>
<?php $this->placeholder('nothing')->captureEnd(); ?>

<?php $this->placeholder('ticket')->captureStart();?>
<h3><?php echo $this->translate('Request Details'); ?></h3>

<table id="info">
    <tr>
        <td><?php echo $this->translate("Stage") . ': '; ?></td>
        <td title="<?php echo $this->ticketStageInfo($ticket->getStage()->getId());?>">
            <div class="mail-16 <?php echo $this->ticketStage($ticket->getStage()->getId());?> btnCenter"></div>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate("Type") . ': '; ?></td>
        <td><?php echo $ticket->getType(); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate("Description") . ': '; ?></td>
        <td><?php echo $ticket->getDescription(); ?></td>
    </tr>
</table>
<a class="btn btn-success return" href="<?php echo $this->url('ticket'); ?>"><?php echo $this->translate("Return"); ?></a>
<?php $this->placeholder('tickets')->captureEnd();?>

<div class="widget">
    <?php if (empty($this->ticket)) {
        echo $this->placeholder('nothing');
    } else {
        echo $this->placeholder('tickets');
    }
    ?>
</div>