<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PhlyContact\Service\ContactControllerFactory'    => __DIR__ .
        '/src/PhlyContact/Services/ContactControllerFactory.php',
    'PhlyContact\Service\ContactCaptchaFactory'       => __DIR__ .
        '/src/PhlyContact/Services/ContactCaptchaFactory.php',
    'PhlyContact\Service\ContactFormFactory'          => __DIR__ .
        '/src/PhlyContact/Services/ContactFormFactory.php',
    'PhlyContact\Service\ContactMailTransportFactory' => __DIR__ .
        '/src/PhlyContact/Services/ContactMailTransportFactory.php',
    'PhlyContact\Service\ContactMailMessageFactory'   => __DIR__ .
        '/src/PhlyContact/Services/ContactMailMessageFactory.php',
    'PhlyContact\Controller\ContactController'        => __DIR__ .
        '/src/PhlyContact/Controller/ContactController.php',
    'PhlyContact\Form\ContactFilter'                  => __DIR__ .
        '/src/PhlyContact/Form/ContactFilter.php',
    'PhlyContact\Form\ContactForm'                    => __DIR__ .
        '/src/PhlyContact/Form/ContactForm.php',
);
