<?php
use Permission\Entity\RoleInterface;

$this->plugin('translate')->setTranslatorTextDomain('Application');
echo $this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('BBC e.V.')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript',
                            array('conditional' => 'lt IE 9',))
                        ->prependFile('/js/bootstrap-collapse.js')
                        ->prependFile('/js/bootstrap.min.js')
                        ->prependFile('/js/jquery-2.0.3.min.js')
        ?>

    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('BBC Nakade') ?></a>
                    <?php echo $this->navigation('app_navigation')->menu()->renderPartial(null, 'topMenu'); ?>
                </div>
            </div>
            <?php echo $this->flashMessenger()->render('success'); ?>
            <?php echo $this->flashMessenger()->render('error'); ?>
        </div>
        <? if ($this->identity()) :?>
        <div id="sidebar" class="span3">
            <?php echo $this->partial('sidebar'); ?>
        </div>
        <?php endif; ?>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <div class="copyright">
                    <?php
                    echo $this->navigation('footer_navigation')->menu()->renderPartial(null, 'siteMenu'); ?>
                    <ul>
                        <li class="version">v0.3.1</li>
                        <li><?php echo $this->translate('All rights reserved.'); ?></li>
                        <li>&copy; 2013-14 Dr. Holger Maerz</li>
                    </ul>
                </div>
            </footer>
        </div>
    </body>
</html>
