<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('BBC e.V.')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript',
                            array('conditional' => 'lt IE 9',))
                        ->prependFile('/js/bootstrap-collapse.js')
                        ->prependFile('/js/bootstrap.min.js')
                        ->prependFile('/js/jquery-2.0.3.min.js')
        ?>

    </head>
    <body>
        <div class="navbar navbar-fixed-top">

            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('BBC Nakade') ?></a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home', 'Application') ?></a></li>




<?php
     if ($user = $this->identity()) {

         echo sprintf('<li><a href="%s">%s</a></li>',
             $this->url('dashboard'),
             $this->translate('Dashboard', 'Application')
         );


        if ($user->getRole()=='admin') {

            $admin = array(

            $this->translate('User', 'Application')   =>
                $this->url('user'),

            $this->translate('Open Results', 'Application')    =>
                $this->url('result'),

            $this->translate('Edit Match Day', 'Application')    =>
                $this->url('timeTable'),

            $this->translate('New Season', 'Application')    =>
                $this->url('createSeason', array('action' => 'create')),

            $this->translate('Appointments', 'Application')    =>
                $this->url('appointmentModerator'),

            $this->translate('Coupons', 'Application')    =>
                $this->url('coupon', array('action' => 'moderate')),

            );

            echo $this->Submenu('Admin', $admin);


        }

        echo sprintf('<li><a href="%s">%s</a></li>',
            $this->url('profile'),
            $this->translate('Profile', 'Application')
        );

        $messages = array(

            $this->translate('Inbox', 'Application')  =>
                $this->url('message'),

            $this->translate('New Message', 'Application')  =>
                $this->url('message', array('action' => 'new')),

             $this->translate('Outbox', 'Application')  =>
                 $this->url('message', array('action' => 'outbox')),


        );

         echo $this->Submenu(
             $this->translate('Messages', 'Application'),
             $messages
         );

        $league = array(

            $this->translate('Schedule', 'Application')   =>
                $this->url('timeTable', array('action' => 'schedule')),

            $this->translate('Standings', 'Application')  =>
                $this->url('actual', array('action' => 'table')),

            $this->translate('results', 'Application')    =>
                $this->url('result', array('action' => 'myResult')),

        );

        echo $this->Submenu(
            $this->translate('League', 'Application'),
            $league
        );

         echo $this->Submenu(
             $this->translate('Appointments', 'Application'),
             array (
                 $this->translate('Shift Date', 'Application')   =>
                     $this->url('appointmentShow', array('action' => 'available')),
                 $this->translate('Confirm', 'Application')   =>
                     $this->url('appointmentShow'),
             )
         );

        echo sprintf('<li style="color:lightblue;line-height:19px;
                padding:10px; padding-left:20px;">%s %s</li>',
            $this->translate('Logged in as ', 'Application'),
            $this->escapeHtml($user->getUsername())
        );

        echo sprintf('<li><a href="%s">%s</a></li>',
            $this->url('login', array('action'=>'logout')),
            $this->translate('Logout', 'Application')
        );

     } else {

        echo sprintf('<li><a href="%s">%s</a></li>',
            $this->url('login'),
            $this->translate('LogIn', 'Application')
        );

     }
?>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>

            <?php //todo: flashMessenger renders not after redirecting
                echo $this->flashMessenger()->render('success'); ?>
            <?php echo $this->flashMessenger()->render('error'); ?>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <div class="copyright">
                    <ul>
                        <li><a href="<?php echo $this->url('privacy', array('action' => 'rules')) ?>">
                                <?php echo $this->translate("Rules", 'Application'); ?>
                            </a>
                        </li>
                        <li><a href="<?php echo $this->url('privacy', array('action' => 'useTerms')) ?>">
                                <?php echo $this->translate("Terms of Use", 'Application'); ?>
                            </a>
                        </li>
                        <li><a href="<?php echo $this->url('imprint') ?>"><?php echo $this->translate("Imprint", 'Application'); ?></a></li>
                        <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate("Contact", 'Application'); ?></a></li>
                        <li><a href="<?php echo $this->url('training') ?>"><?php echo $this->translate("Location", 'Application'); ?></a></li>
                        <li class="version">v0.3.1</li>
                        <li><?php echo $this->translate('All rights reserved.', 'Application') ?></li>
                        <li>&copy; Copyright 2013-2014 Dr. Holger Maerz</li>
                    </ul>
                </div>
            </footer>
        </div> <!-- /container -->
        <?php //echo $this->inlineScript() ?>

    </body>
</html>
