<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('User'); 
$title = $this->translate('Failure');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p style="font-size:larger;margin: 10px 0;">
<?php echo $this->translate('The given email adress was not found.'); ?>  
<br/>
<?php echo $this->translate('Please try again with the registered mail.');?>
</p>
