<?php
$this->plugin('translate')->setTranslatorTextDomain('User'); 
$title = $this->translate('Forgot Password');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p style="font-size:larger;margin: 10px 0;"><?php echo $this->translate('Please enter your registered mail adress.'); ?>  
<br/><?php echo $this->translate('We will send your new credentials immediatley to that adress.');?></p>


<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formCollection($this->form);
echo $this->form()->closeTag();
?>


