<?php
// module/Impressum/view/impressum/impressum/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('Blog');
$title = $this->translate("News");
$this->headTitle($title);
/* @var $post \Blog\Entity\Post */
?>

<div class="blog">

<?php foreach ($blog as $post) : ?>
<div style="border: 1px solid red; max-width:800px;">
    <h3><?php echo $post->getTitle();?></h3>
    <p style="font-size:13px;line-height:1.3;"><?php echo $post->getContent();?><br/>
    <span style="color:grey; font-size:smaller;line-height:0;padding:0;">gepostet am <?php echo $post->getDate()->format('d.m.y');?></span>
    </p>
</div>
<?php endforeach; ?>
</div>

