<?php
// module/Impressum/view/impressum/impressum/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('Blog');
$title = $this->translate("News");
$this->headTitle($title);
/* @var $post \Blog\Entity\Post */
?>

<a class="btn"><</a>
<?php $post = $blog[0]; ?>
<div class="post">
    <h3><?php echo $post->getTitle();?></h3>
    <p><?php echo $post->getContent();?></p>
    <div class="info">gepostet am <?php echo $post->getDate()->format('d.m.y');?></div>
</div>
<a class="btn">></a>

