<?php
$this->plugin('translate')->setTranslatorTextDomain('Blog');
$title = $this->translate("News");
$this->headTitle($title);
/* @var $post \Blog\Paginator\CarouselPaging */
?>

<a class="btn" title="<?php echo $this->translate('previous')?>"
   href="<?php echo $this->url('home', array('action' => 'index', 'page' => $post->getPrevious()));?>"><</a>
<div class="post">
    <h3><?php echo $post->getActualPost()->getTitle();?></h3>
    <p><?php echo $post->getActualPost()->getContent();?></p>
    <div class="info">
        <?php echo $this->translate("posted at"). ' ' . $post->getActualPost()->getDate()->format('d.m.y');?>
    </div>
</div>
<a class="btn" title="<?php echo $this->translate('next')?>"
   href="<?php echo $this->url('home', array('action' => 'index', 'page' => $post->getNext()));?>">></a>

