<?php
$this->plugin('translate')->setTranslatorTextDomain('Moderator');
/* @var $support \Moderator\Entity\SupportRequest */
$this->headTitle('Moderator View');

?>

<?php $this->placeholder('nothing')->captureStart();?>
    <h3><?php echo $this->translate('No Support Requests found'); ?></h3>
<?php $this->placeholder('nothing')->captureEnd(); ?>

<?php $this->placeholder('manager')->captureStart();?>
    <h3><?php echo $this->translate('My Support Requests'); ?></h3>
    <hr/>
    <a class="addUser buttons-32 user-add-32" title="<?php echo $this->translate("add League Manager"); ?>" href="
    <?php echo $this->url('manager', array('action' => 'add')); ?>"></a>
<?php //echo $this->paginationControl($this->paginator, 'Sliding', 'moderator'); ?>
    <table class="table profile">
        <tr>
            <th><?php echo $this->translate("ID"); ?></th>
            <th><?php echo $this->translate("League"); ?></th>
            <th><?php echo $this->translate("Subject"); ?></th>
            <th><?php echo $this->translate("Author"); ?></th>
            <th><?php echo $this->translate("Date"); ?></th>
            <th><?php echo $this->translate("Stage"); ?></th>
            <th><?php echo $this->translate("Details"); ?></th>
        </tr>
        <?php foreach ($this->supportRequests as $support) : ?>
            <tr style="background-color:<?php
            echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
                <td style="text-align: right"><?php echo $support->getId(); ?></td>
                <td><?php echo $support->getAssociation()->getName();?></td>
                <td><?php echo $support->getSubject(); ?></td>
                <td><?php echo $support->getMessages()->first()->getAuthor()->getShortName();?></td>
                <td><?php echo $support->getMessages()->first()->getDate()->format('d.m.y H:i'); ?></td>
                <td><?php echo $support->isDone(); ?></td>
                <td><a href="<?php echo $this->url('support', array('action' => 'myInquiries', 'id' => $support->getId()))?>" class="button"><div class="buttons-16 info-16 btnCenter"></div></a>

                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <p><?php //echo $this->translate("Total") . ' ' . $this->paginator->getTotalItemCount() . ' ' . $this->translate("League Manager"); ?></p>
<?php $this->placeholder('manager')->captureEnd();

if (empty($this->supportRequests)) {
    echo $this->placeholder('nothing');
} else {
    echo $this->placeholder('manager');
}
