<?php
use \League\View\Helper\Sort;
$this->plugin('translate')->setTranslatorTextDomain('League');
$this->headTitle('table');

/* @var $player \League\Entity\Player */
/* @var $tournament \Season\Entity\League */
/* @var $pagination \League\Pagination\LeaguePagination */

$title = $this->translate("%NAME% League - %NUMBER%.Season");
$tb1 = 'TB1';
$tb2 = 'TB2';
$tb3 = 'TB3';

if (!is_null($tournament)) {
    $title = str_replace("%NAME%", $tournament->getSeason()->getAssociation()->getName(), $title);
    $title = str_replace("%NUMBER%", $tournament->getSeason()->getNumber(), $title);
    $tb1 = $tournament->getSeason()->getTieBreaker1();
    $tb2 = $tournament->getSeason()->getTieBreaker2();
    $tb3 = $tournament->getSeason()->getTieBreaker3();
}
?>

<?php $this->placeholder('standings')->captureStart(); ?>
    <div class="widget">
        <h3><?php echo $title; ?></h3>
        <?php $leagueNo = $this->paginator->getCurrentPageNumber() ?>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'league'); ?>
        <table class="table standings">
            <tr>
                <th title="<?php echo $this->translate('Position');?>">P</th>
                <th title="<?php echo $this->translate('Player');?>">
                    <a href="<?php echo $this->sort(Sort::BY_NAME, $leagueNo); ?>">
                        <?php echo $this->translate('Name')?>
                    </a>
                </th>
                <th title="<?php echo $this->translate('played games')?>">
                    <a href="<?php echo $this->sort(Sort::BY_PLAYED_GAMES, $leagueNo); ?>">
                        <?php echo $this->translate('GP')?>
                    </a>
                </th>
                <th title="<?php echo $this->translate('Wins')?>">
                    <a href="<?php echo $this->sort(Sort::BY_WON_GAMES, $leagueNo); ?>">
                        <?php echo $this->translate('W')?>
                    </a>
                </th>
                <th title="<?php echo $this->translate('Jigo')?>">
                    <a href="<?php echo $this->sort(Sort::BY_DRAW_GAMES, $leagueNo);?>">
                        <?php echo $this->translate('J')?>
                    </a>
                </th>
                <th title="<?php echo $this->translate('Lost')?>">
                    <a href="<?php echo $this->sort(Sort::BY_LOST_GAMES, $leagueNo);?>">
                        <?php echo $this->translate('L')?>
                    </a>
                </th>
                <th title="<?php echo $this->translate('Points')?>">
                    <a href="<?php echo $this->sort(Sort::BY_POINTS, $leagueNo);?>">
                        <?php echo $this->translate('Pt')?>
                    </a>
                </th>
                <th title="<?php echo $tb1->getDescription()?>">
                    <a href="<?php echo $this->sort(Sort::BY_FIRST_TIEBREAK, $leagueNo);?>">
                        <?php echo $tb1->getName()?>
                    </a>
                </th>
                <th title="<?php echo $tb2->getDescription()?>">
                    <a href="<?php echo $this->sort(Sort::BY_SECOND_TIEBREAK, $leagueNo);?>">
                        <?php echo $tb2->getName()?>
                    </a>
                </th>
                <th title="<?php echo $tb3->getDescription(); ?>">
                    <a href="<?php echo $this->sort(Sort::BY_THIRD_TIEBREAK, $leagueNo);?>">
                        <?php echo $tb3->getName()?>
                    </a>
                </th>
            </tr>
            <?php foreach ($this->table as $player) : ?>
                <tr style="background-color:<?php  echo $this->highlightUser($player->getUser()); ?>">
                    <td><?php echo $this->getPosition($player) ?></td>
                    <td class="name"><?php echo $player->getUser()->getShortName();?></td>
                    <td><?php echo $player->getGamesPlayed(); ?></td>
                    <td><?php echo $player->getGamesWin();?></td>
                    <td><?php echo $player->getGamesDraw();?></td>
                    <td><?php echo $player->getGamesLost();?></td>
                    <td><?php echo $player->getGamesPoints();?></td>
                    <td><?php echo $player->getFirstTiebreak();?></td>
                    <td><?php echo $player->getSecondTiebreak();?></td>
                    <td><?php echo $player->getThirdTiebreak();?></td>

                </tr>
            <?php endforeach; ?>
        </table>
    </div>
<?php $this->placeholder('standings')->captureEnd(); ?>


<?php

if (!is_null($this->table)) {
    echo $this->placeholder('standings');
}




