<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('League'); 
$headline = $this->translate("Top League") . $this->number;
$this->headTitle($headline);

?>

<h3><?php echo $this->escapeHtml($headline); ?></h3>

<table class="table" style="width:8em;margin-top: 0.5em;">
<tr>
    <th title="<?php echo $this->translate('Position')?>">P</th>
    <th title="<?php echo $this->translate('Player')?>"><?php 
        echo $this->translate('Name')?></th>
    <th title="<?php echo $this->translate('Played games')?>"><?php 
        echo $this->translate('GP')?></th>
    <th title="<?php echo $this->translate('Wins')?>"><?php 
        echo $this->translate('W')?></th>
    <th title="<?php echo $this->translate('Tie-breaker')?>"><?php 
        echo $this->translate('Hahn')?></th>
</tr>
<?php foreach ($this->users as $user) : ?>
<tr style="background-color:<?php 
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $this->position($user); ?></td>
    <td><?php echo $this->escapeHtml($this->player($user->getPlayer()));?></td>
    <td><?php echo $this->escapeHtml($user->getGamesPlayed());?></td>
    <td><?php echo $this->escapeHtml($user->getWin());?></td>
    <td><?php echo $this->escapeHtml($user->getTiebreaker1());?></td>
    
</tr>
<?php endforeach; ?>
</table>

