<?php
$this->plugin('translate')->setTranslatorTextDomain('League');
$this->headTitle("Top Table");

/* @var $player \League\Entity\Player */
/* @var $tournament \Season\Entity\League */
$title = $this->translate("%NAME% League %YEAR%");

if (!is_null($tournament)) {
    $title = str_replace("%NAME%", $tournament->getSeason()->getAssociation()->getName(), $title);
    $title = str_replace("%YEAR%", $tournament->getSeason()->getStartDate()->format('Y'), $title);
}
$leagueInfo = $this->translate("%No%.League");
$leagueInfo = str_replace('%No%', $tournament->getNumber(), $leagueInfo);

$matchDayInfo = $this->translate("%No%.Match Day");
$matchDayInfo = str_replace('%No%', $this->matchDay, $matchDayInfo);

?>

<?php $this->placeholder('standings')->captureStart();?>
    <div class="widget">
        <h3 style="margin: 0;"><?php echo $title; ?></h3>
        <h5><?php echo $leagueInfo . ' - ' . $matchDayInfo; ?></h5>
        <table class="table" style="width: auto; margin-top: 0.5em;">
            <tr>
                <th title="<?php echo $this->translate('Position');?>">No</th>
                <th title="<?php echo $this->translate('Player');?>">
                    <?php echo $this->translate('Name')?></a></th>
                <th title="<?php echo $this->translate('Games')?>">
                    <?php echo $this->translate('G')?></th>
                <th title="<?php echo $this->translate('Points')?>">
                    <?php echo $this->translate('P')?></th>
                <th title="<?php echo $this->translate('Tiebreaker')?>">
                    <?php echo $this->translate('TB')?></th>
            </tr>
            <?php foreach ($this->table as $player) : ?>
                <tr style="background-color:<?php
                echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
                    <td><?php echo $this->getPosition($player); ?></td>
                    <td><?php echo $player->getUser()->getShortName();?></td>
                    <td><?php echo $player->getGamesPlayed(); ?></td>
                    <td><?php echo $player->getGamesPoints();?></td>
                    <td><?php echo $player->getFirstTiebreak();?></td>

                </tr>
            <?php
            endforeach; ?>
        </table>
    </div>
<?php $this->placeholder('standings')->captureEnd();?>


<?php if (!is_null($this->table)) {
    echo $this->placeholder('standings');
}
