<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('User'); 
$title = $this->translate('Verification Failed');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p style="font-size:larger;margin: 10px 0;">
    <?php echo $this->translate("Activation of your account failed."); ?>
    <br/>
    <?php echo $this->translate("Probably your credentials are expired."); ?>
    <br/>
    <?php echo $this->translate("Read your activation mail for more information."); ?>
    <br/>
    <br/>
    <?php echo $this->translate("YOU DO NOT HAVE TO REGISTER."); ?>
    <br/>
    <?php echo $this->translate("Just request a new password by using the 'forgot password' option."); ?>
</p>
