<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('User'); 
$title = $this->translate('Account Verified');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p style="font-size:larger;margin: 10px 0;">
    <?php echo $this->translate("Thank you for your activation."); ?>
    <br/>
    <?php echo $this->translate("You can now sign in using your credentials."); ?>
</p>

