<?php
// module/user/view/user/user/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('User');
$title = $this->translate('My Invitations');
$this->headTitle($title);
/* @var $profile \User\Entity\User */
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table profile">
    <tr>
        <th><?php echo $this->translate("ID"); ?></th>
        <th><?php echo $this->translate("Sent To"); ?></th>
        <th><?php echo $this->translate("Date"); ?></th>
        <th><?php echo $this->translate("Expiry Date"); ?></th>
        <th><?php echo $this->translate("Registered"); ?></th>
    </tr>
    <tr>
        <?php
        /* @var $coupon \User\Entity\Coupon */
        foreach ($this->coupons as $coupon) : ?>
    <tr style="background-color:<?php
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
        <td style="text-align: right"><?php echo $coupon->getId(); ?></td>
        <td><?php echo $coupon->getEmail(); ?></td>
        <td><?php echo $coupon->getCreationDate()->format('d.m.y H:i');?></td>
        <td><?php echo $coupon->getExpiryDate()->format('d.m.y H:i');?></td>
        <td><?php if ($coupon->isUsed()) : ?>
                <div class="arrows-16 active-16 btnCenter"></div>
                <?php else : ?>
                <div class="mail-16 time-16 btnCenter"></div>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
