<?php
$this->plugin('translate')->setTranslatorTextDomain('Application');
$title = $this->translate("FAQ");
$this->headTitle($title);
?>
<div id="termsOfUse">
<h1><?php echo $this->translate("Häufig gestellte Fragen"); ?></h1>
<h2>(letzte Aktualisierung vom 01.09.2014)</h2><br>
<dl class="list">

<dt>Was ist Nakade?</dt>
<dd>
<ol>
    <li>Nakade wurde entwickelt, um Turniere und Ligen für das Go Spiel einfacher und unkomplizierter veranstalten zu
        können.</li>
</ol>
</dd>

<dt>Warum sollte ich mich für Nakade entscheiden statt meine Veranstaltungen wie bisher manuell zu verwalten?</dt>
<dd>
    <ol>
        <li>Ein Umstieg auf Nakade kann besonders sinnvoll sein, wenn zuvor Schwierigkeiten bei der Terminfindung oder
            auch sonst der Kommunikation zwischen den Spielern registriert wurden.<br>
            Nakade denkt mit und erinnert alle Schlafmützen rechtzeitig an ihre Spieltermine oder hilft
            notfalls dabei einen neuen Termin zu finden.</li>

        <li>Die Spieler werden vom System interaktiv einfach und benutzerfreundlich geführt. Der Aufwand für die
            Turnierleitung ist gleich Null, sodass Sie sich um die Gestaltung des Turniers kümmern können statt allen
            Teilnehmern hinterherzurennen. Die Ergebnisse werden anschaulich in Tabellen und Diagrammen dargestellt.
        </li>
    </ol>
</dd>


<dt>Was haben Spieler von der Nutzung von Nakade? Ist das nicht viel zu kompliziert?</dt>
<dd>
    <ol>
        <li>Zugegeben, eine weitere Registrierung und noch ein Konto klingen zunächst erschreckend umständlich. Außer
            des flüssigeren und automatisierten Turnierverlaufs, profitieren die Spieler von der Erstellung eines
            eigenen Nakade Kontos auch noch von einem Zugang zu weiteren hochkarätigen Turnieren, die mit der gewohnten
            Übersichtlichkeit dargestellt werden. Somit können Ergebnisse rund um die Welt in einem einzigen Tool
            abgerufen werden.</li>
    </ol>
</dd>


</div>