<?php
// module/Privacy/view/Privacy/index.phtml:
$this->plugin('translate')->setTranslatorTextDomain('Application');
$title = $this->translate("Terms of Use");
$this->headTitle($title);
?>
<div id="termsOfUse">
<h1><?php echo $this->translate("Allgemeine Geschäftsbedingungen"); ?></h1>
<h2>(Gültig seit 31.07.2014)</h2><br>
<dl class="list">
<dt>Wesen des Angebotes</dt>
<dd>
<p>Unter der Domain <a href="http://nakade.de" target="_blank">nakade.de</a> bietet der Berliner Baduk Club e.V.
(im Folgenden: „Nakade“ oder „wir“) eine auf die Organisation von Turnieren und Liga-Spielen ausgerichteten
online Service.<br>
Nakade bietet den Nutzern im Übrigen eine Kommunikationsplattform an, die eine direkte Kontaktaufnahme untereinander
ermöglicht.<br>
Nakade behält sich vor, die angebotenen Dienste zu ändern, einzustellen oder neue Dienste anzubieten.
</p>
</dd>
<dt>Kostenlose Registrierung</dt>
<dd>
<p>
Jeder Nutzer, der aktiv an den Serviceangebot von Nakade (Spielorganisation, Kommunikation, Statistiken, etc.), muss
sich hierzu bei nakade.de registrieren. Durch die Registrierung entstehen dem Nutzer keine Kosten.<br>
Die Registrierung bei Nakade erfolgt unter <a href="http://nakade.de/register" target="_blank">http://nakade.de/register</a>.
Es werden der vollständige Name, eine Emailadresse und ein frei wählbarer Benutzername von dem Benutzer benötigt.
Der Nutzer erhält bei seiner Anmeldung eine Email zur Bestätigung seiner Email-Adresse. Wird die Email-Adresse nicht
innerhalb der gesetzten Frist bestätigt, werden alle Nutzerdaten gelöscht. Der Benutzer verpflichtet sich, Benutzernamen
sowie Passwort geheim zu halten. Kein Nutzer darf mehr als ein Nutzerprofil registrieren.
</p>
</dd>
<dt>Verfügbarkeit und Nutzung des Angebotes</dt>
<dd>
<p>
Grundsätzlich steht die Nutzung jeder natürlichen und geschäftsfähigen Person, die gewillt ist sich an diese
Nutzungsbedingungen zu halten und zu dem Angebot und Inhalten konstruktiv beizutragen, frei.
Der Zugang zum Angebot und dessen Nutzung kann jedoch nicht rechtlich beansprucht werden. Wir behalten uns in jedem Fall
unsere Zustimmung vor.<br>
Eine uneingeschränkte Verfügbarkeit des Angebots für die Nutzer ist technisch nicht zu leisten, da unser Angebot Zugriff
auf Telekommunikationsnetze und -verbindungen anderer Netzbetreiber und anderer Diensteanbieter voraussetzt, auf deren
Leistungen wir keinen Einfluss haben. Soweit wir Einfluss auf Unterbrechungen, z.B. notwendige Maßnahmen (wie Pflege-
und Wartungsarbeiten an Software und Hardware) haben, sind wir bemüht Unterbrechungen des Angebotes zeitlich so kurz wie
möglich zu halten und diese ggf. auch anzukündigen.
</p>
<p>Für online Go-Partien muss eine Software eines Drittanbieters (Kiseido Go Server, KGS) installiert werden. KGS ist ein
in der Community allgemein bekannter Service zum Spielen von Go-Partien über das Internet. Für die Nutzung dieses Services
von KGS ist eine zusätzliche Registrierung beim Anbieter notwendig. Hat keinen Einfluß auf das Dienstangebot von KGS und
übernimmt keine Haftung für etwaige Schäden oder Ausfälle. Zudem ist der Nutzer bei Teilnahme an Turnieren verpflichtet,
sich selbstständig und rechtzeitig mit der Funktionweise des Go-Clients auseinandersetzen.</p>

</dd>

<dt>Nutzerpflichten und besondere Nutzungsbedingungen</dt>
<dd>
<p>
Grundlage der Nutzung sind die nachfolgenden Bestimmungen, die wesentliche Vertragspflichten der Nutzer enthalten:
</p>


<dl class="sublist">

<dt>Unzulässige Inhalte, kommerzielle Werbung, unerlaubte Nutzungsweisen, Links</dt>
<dd>

<p>Wir weisen ausdrücklich darauf hin, dass folgende Nutzungshandlungen oder Inhalte nicht zulässig sind und wir bzw. die
Moderatoren bereits bei einem ersten Zuwiderhandeln neben der Entfernung des Inhalts bzw. Beitrags weitere Konsequenzen
bis zu einer sofortigen Sperrung des Nutzers für alle Dienste ziehen werden:</p>

<ol class="list">
    <li>
        Alle Beiträge, Tätigkeiten und Handlungen, die gesetzeswidrige, insbesondere beleidigende, pornographische oder
        sonst gegen Jugendschutzbestimmungen verstoßende Handlungen darstellen oder diese verherrlichen, sowie alle
        Beiträge, in denen natürliche oder juristische Personen sonst in ihrer Ehre bzw. dem geschäftlichen Ansehen
        herabgesetzt oder ihr geschäftlicher oder sonstiger Ruf geschädigt wird.
    </li>
    <li>Das Offenlegen oder zugängig machen von persönlichen Zugangsdaten zu Nakade, seien es eigene Daten oder fremde Daten.</li>
    <li>Die Verletzung von Urheber- oder Markenrechten Dritter, insbesondere im Falle eines Verstoßes gegen den nachfolgenden
        <a href="#rights">Unterpunkt</a>.
    </li>
    <li>Jede Form von Diskriminierung anderer Menschen sowie sonstige schwerwiegende Verstöße gegen die
        <a href="#netiquette">Netiquette</a>.
    </li>
    <li>
        Das Setzen von Links zu anderen Seiten oder Diensten, die gesetzeswidrigen, beleidigenden oder pornografischen
        Inhalt oder sonst unerwünschte Inhalte aufweisen sowie jede Form von Werbung oder kommerzieller Nutzung ohne
        unsere ausdrückliche vorherige Zustimmung.
    </li>
    <li>
        Das automatische Auslesen der auf unserer Seite befindlichen Daten sowie der Aufbau eigener Suchsysteme,
        Dienste und Verzeichnisse unter Zuhilfenahme der auf nakade.de abrufbaren Inhalte und Dienste.
        Ferner das Versenden von Kettenmails bzw. -briefen per Mail, jegliche Durchführung von Strukturvertrieb bzw.
        -vertriebsunterstützung, auch sog. Multi-level-marketing.
    </li>
    <li>Das Hochladen von Software, Skripten, Dateien und sonstigen Mechanismen/Techniken, die dazu geeignet sind,
        nakade.de oder dessen User, deren Computer, die Server von nakade.de  oder die auf den Rechnern der User oder
        den Servern von nakade.de verwendete Software, auszuspionieren, zu attackieren, lahm zu legen oder in sonstiger
        Form zu beeinträchtigen oder zu einer Beeinträchtigung Beihilfe zu leisten.</li>
</ol>

<p>Unerwünscht sind außerdem folgende Nutzungshandlungen und Inhalte:</p>

<ol class="list">
    <li>Threads, Beiträge oder Kommunikation mit politischen oder religiösen Inhalten.</li>
    <li>Threads, Beiträge oder Kommunikation mit erotischem oder sexuell geprägtem Inhalt.</li>
</ol>

<p>Das Setzen von Links ist nur erlaubt, wenn diese zu gewünschten Informationen im Sinne der Nakade-Foren dienen.
Über die Zulässigkeit entscheiden wir oder der jeweilige Moderator im Einzelfall, sobald wir Kenntnis von einem Link erhalten.
<br>Da wir eine Haftung von unserer Seite für die von unseren Nutzern gesetzten Links nach heute geltender Rechtssprechung
nicht mit völliger rechtlicher Sicherheit auch für die Zukunft ausschließen können, behalten wir uns vor, auch Links,
die einmal zugelassen worden sind, zu einem späteren Zeitpunkt ohne Angabe von Gründen jederzeit von unserer Seite zu
entfernen. Die Nutzer, deren Links zugelassen worden sind, verpflichten sich, die Inhalte der gelinkten Seiten regelmäßig
zu prüfen und uns im Zweifel davon zu unterrichten, dass sich diese Inhalte geändert haben. Wir bitten alle Nutzer, uns
auf etwaige unzulässige Threads, Beiträge, Links oder Etiketteverstöße durch eine Mail an info@nakade.de hinzuweisen.</p>
</dd>

<dt><a name="rights"></a>Urheber- und Nutzungsrechte, gewerbliche Schutzrechte und  Markenrechte, Haftung</dt>
<dd>
<p>
Alle Nutzer erklären sich damit einverstanden, dass Nakade für die Plattform nakde.de in den Foren, im Liga- bzw Turnierbereich
oder an sonstiger Stelle von ihnen eingestellten Daten auch nach Einstellung der Nutzung durch den Nutzer weiterhin von
Nakade selbst oder durch Nakade benannte Dritte für die Zwecke des Portalbetriebes elektronisch vervielfältigt
und zum Download (§ 19 UrhG) bereitgehalten werden dürfen. Darüber hinaus darf Nakade die Inhalte im Rahmen seines
Ligabetriebs bzw. Newsletters per Mail an andere Nutzer versenden und Dritten gestatten, per RSS-Feed auf die Inhalte
zurückzugreifen und diese auf ihren Internetseiten zum  download anzubieten.
</p>
<p>
Die Nutzer stehen dafür ein, dass die von ihnen eingestellten bzw. zur Verfügung gestellten Daten und Dateien, wie
vorstehend beschrieben, genutzt und veröffentlicht werden dürfen. Im Zweifel dürfen Inhalte nicht hochgeladen oder sonst
eingestellt werden, wenn der Nutzer die urheberrechtliche Situation nicht eindeutig zu seinen und zu unseren
Gunsten beurteilen kann.
</p>
<p>
Sofern eine elektronische Vervielfältigung oder Verbreitung oder die Zugänglichmachung gemäß § 19a UrhG durch uns in Bezug
auf Inhalte, die ein Nutzer hochgeladen hat bzw.die uns von einem Nutzer zur Verfügung gestellt worden sind, zu berechtigten
Unterlassungs- und Schadensersatzansprüchen von dritter Seite führt, ist der Nutzer verpflichtet, Nakade und seine
gesetzlichen Vertreter unverzüglich von diesen Ansprüchen freizustellen und die Kosten der außergerichtlichen und einer
etwaigen gerichtlichen Rechtsverteidigung zu übernehmen. Dies gilt insbesondere in den Fällen, in denen der Nutzer es
schuldhaft unterlassen hat, uns auf Nutzungsbeschränkungen hinzuweisen bzw. die Inhalte eingestellt hat, obschon er
wusste oder hätte wissen können, dass daran entgegenstehende Rechte Dritter bestehen.</p>
<p>
Besondere Vorsicht ist insbesondere bei dem Hochladen von Fotografien und sonstigen Bildmaterialien geboten, die nicht
von dem Nutzer selbst stammen. Dieses Material sollte ausdrücklich als gemeinfrei gekennzeichnet sein. Sofern die Angabe
eines Urhebers oder Fotografen im Zusammenhang mit der Nutzung vorgegeben ist, müssen wir darüber vorab per Mail
unter Angabe der Quelle informiert werden.</p>
<p>
Schadensersatzansprüche gegen Nakade können nur geltend gemacht werden, wenn wir schuldhaft gegen unsere wesentlichen
Vertragspflichten verstoßen haben. Trifft uns nur ein sehr geringes Verschulden oder sind nur unwesentliche Nebenpflichten
verletzt, schließen wir jede Haftung unsererseits aus. Der Höhe nach sind alle etwaigen Schadensersatzansprüche unserer
Nutzer gegen uns beschränkt auf den vorhersehbaren Schaden.
</p>
<a name="netiquette"></a>
</dd>

<dt>Umgangston und Netiquette</dt>
<dd>
<p>
Unsere Moderatoren und Administratoren sind berechtigt, die Entscheidung über die Eignung von Beiträgen sowie die
Kategorisierung in Eigenverantwortung für uns zu treffen und auch berechtigt, Threads sowie Beiträge ohne Angabe von Gründen zu entfernen.
</p>
<p>
Alle Nutzer sind verpflichtet, sich in Umgangston und Netiquette an die Grundregeln der gegenseitigen Toleranz und des
höflichen Umgangs zu halten. Als solche setzen wir voraus:
</p>
<ol class="list">
    <li>Wahrung des gegenseitigen Respekts und konventioneller Höflichkeit – Grußformeln gehören zum Anstand.</li>
    <li>Keine Herabsetzungen oder Beleidigungen, im Zweifel noch einmal genau prüfen und abwägen, was man geschrieben hat.</li>
    <li>Wer an einem echten Meinungsaustausch nicht teilnehmen möchte, weil er z.B. darauf beharrt, dass seine Meinung
        die einzig wahre ist, sollte sich einen öffentlichen Disput ersparen.
    </li>
    <li>Im Zweifel richtet man sich nach den Regeln der Gemeinschaft, insbesondere, wenn man ihr angehören möchte.</li>
    <li>Go- und Schach haben für uns einen hohen kulturellen Wert. Es wird erwartet, dass die Nutzer dazu beitragen,
        daß diese Brettspiele in der Öffentlichkeit wie auch Community positiv wahrgenommen werden können.
    </li>
</ol>
<p>
In Folge dessen werden alle Herabsetzungen und persönliche Angriffe in allen unseren Nakade-Foren nicht toleriert,
ungeachtet dessen, ob sich solche Äußerungen direkt gegen die anderen Nutzer, die Moderatoren/Administratoren, gegen
Dritte oder gegen andere interne oder externe beteiligte oder unbeteiligte Personengruppen richten.
Gleiches gilt für alle Beiträge, die gegen geltendes Recht verstoßen.
</p>
</dd>
</dl>

</dd>

<dt>Moderation, Rechte der Moderatoren</dt>
<dd>
 <p>
In dem jeweiligen Forum unterstützen Administratoren und Moderatoren die Nutzer. Sie entscheiden über die Inhalte und
Regelauslegungen (s. Reglement). Damit stellen sie die Einhaltung dieser Nutzungsbedingungen sicher,
wenn nötig auch durch das Verschieben, Sperren oder Löschen von Beiträgen oder den Ausschluss von Mitgliedern sowie den
Fortbestand eines Forums. Diese Maßnahmen werden im Sinne der Nutzungsbedingungen und im Sinne eines guten Forenklimas
durchgeführt und unterliegen keinerlei Erklärungspflicht.
Die Administratoren und Moderatoren tun dies im Interesse aller Nutzer und verdienen daher Respekt und Unterstützung.
</p>
<p>
Die vorstehenden Bestimmungen gelten entsprechend für Gruppen, die innerhalb der Community gegründet werden.
Der Gründer der Gruppe übernimmt hierbei die Rolle des Chefmoderators bzw. Ligachefs und selber (Gruppen)Moderatoren bzw.
Ligamanager bestimmen kann, jedoch auch die Verpflichtung hat, auf die Einhaltung dieser AGB innerhalb seiner Gruppe zu
achten und geeignete Maßnahmen zu treffen. Dort können erforderlichenfalls der/die Moderatoren und Administratoren
die Rolle und Aufgaben des Gruppengründers übernehmen. Die Disziplinarmöglichkeiten der von Nakade ernannten
Administratoren und Moderatoren sind innerhalb der Gruppen jedoch nicht eingeschränkt. Die Einhaltung der AGB in allen
Arten von Gruppen kann stichprobenartig von den von Nakade ernannten Administratoren und Moderatoren überprüft werden.
</p>
<p>
Im Falle von Regelstreitigkeiten im Spielbetrieb hat jeder Nutzer das Recht, das Schiedsgericht zu berufen. Dieses
Schiedsgericht wird von Nakade ernannt und trifft Entscheidungen auf der Basis des Regelwerks. Das Schiedsgericht soll
aber auch versuchen zwischen den Streitparteien zu vermitteln bzw. Stellungnahmen der Betroffenden entgegen zu nehmen.
Eine Schiedsentscheidung muss auf Nachfrage begründet werden. Die Entscheidung wird von den Moderatoren umgesetzt.
</p>
<p>
Sofern die Administratoren und Moderatoren außerhalb ihres Tätigkeitsbereiches private Meinungen äußern, gelten für sie
die gesamten Nutzungsbedingungen. Wir bitten jedoch unsere Moderatoren und Administratoren, sich in ihrer jeweiligen
Funktion absolut neutral und unabhängig in Bezug auf ihre eigene Auffassung bzw. Meinung zu verhalten und diese nicht in
Wahrnehmung ihrer Funktionen in diesem Dienst zu äußern.
</p>
<p>
Bei Verstößen gegen die Nutzungsbedingungen behält sich Nakade folgende Maßnahmen vor:
</p>
<ol class="list">
    <li>Als erste Maßnahme erhält der Nutzer eine Ermahnung per Email.</li>
    <li>Danach erhält der Nutzer nötigenfalls eine Abmahnung per Email.</li>
    <li>Als dritte und letzte Maßnahme wird, je nach Erforderlichkeit und Schwere des Verstoßes, der Zugang des Nutzers
        auf Zeit oder dauerhaft gesperrt.
    </li>
</ol>
<p>
Nakade behält sich ferner vor, bei massiven erstmaligen Verstößen gegen die Nutzungsbedingungen oder gegen Gesetze auch
eine sofortige und vollständige Sperrung des Zuganges für den Nutzer durchzuführen.<br>
Nakade kann nicht für eine gegebenenfalls angegebene Identität eines Nutzers einstehen.
Es ist Nakade infolge der Vielzahl von Kommunikationsvorgängen  und –angeboten nicht möglich, diese vollständig zur
Kenntnis zu nehmen. Wir bitten alle Nutzer, uns auf etwaige unseriöse oder ungesetzliche Verhaltensweisen per Mail an
info@nakade.de hinzuweisen.<br>
</p>
</dd>
<dt>Beendigung der Nutzung</dt>
<dd>
<p>
Jeder Nutzer kann die unentgeltliche Nutzungsmöglichkeit jederzeit ohne Angabe von Gründen beenden.
Hierfür kann der Nutzer einen Admin bitten, seinen Zugang zu deaktivieren.
<br>
Eingestellte Inhalte und der Benutzername bleiben auch nach einer Beendigung Bestandteil des öffentlich abrufbaren Inhaltsangebots bestehen.
</p>
</dd>

<dt>Datenschutz, Einwilligung des Nutzers</dt>
<dd>
<p>
Die von den Nutzern der Dienste/Mitgliedschaften im Nutzerkonto (Account) eingetragenen persönlichen Daten
(Name, Vorname, Adresse usw.) werden von nakade.de nicht ohne Zustimmung des Nutzers an Dritte weitergegeben.
Der Nutzer kann seine persönlichen Daten zu jedem Zeitpunkt ändern. Das Nutzerkonto und der damit verbundene Benutzername
selbst kann nicht entfernt oder abgeändert werden. Der Nutzer hat die Möglichkeit seinen nach Außen sichtbaren Namen durch
die Eintragung eines Spitznamens und bestätigter Anonymisierung ("immer Spitznamen verwenden") im Profil zu anonymisieren.
</p>
</dd>

<dt>Allgemeine Bestimmungen</dt>
<dd>
<p>
Diese Nutzungsbedingungen gelten ab dem 31.07.2014. Wir behalten uns vor, die Nutzungsbedingungen für die Zukunft zu ändern
und werden alle Nutzer auf neue Nutzungsbedingungen an geeigneter Stelle in unserem Dienst oder per Mail rechtzeitig
hinweisen. Jeder Nutzer hat jederzeit das Recht, den neuen Nutzungsbedingungen zu widersprechen.
wir haben in diesem Fall das Recht, das Nutzungsverhältnis zu beenden.
</p>
</dd>
</dl>

</div>