<?php
// module/user/view/user/user/index.phtml:

$title = 'Participants';
$this->headTitle($title);
?>

<?php $this->placeholder('noseason')->captureStart();?>
<h3><?php echo $this->translate('No players found')?></h3>
<?php $this->placeholder('noseason')->captureEnd(); ?>

<?php $this->placeholder('players')->captureStart();?>
<h3><?php echo $this->escapeHtml(
                $this->translate('Participants of the new Season')); 
 ?></h3>

<table class="table" style="margin-top: 0.5em;">
<tr>
    <th title="<?php echo $this->translate("player's name"); ?>"><?php 
        echo $this->translate("Name"); ?></th>
    <th title="<?php echo $this->translate("number of league"); ?>"><?php 
        echo $this->translate("League"); ?></th>
    <th title="<?php echo $this->translate("edit player"); ?>"><?php 
        echo $this->translate("edit"); ?></th>
    <th title="<?php echo $this->translate("remove from league"); ?>"><?php 
        echo $this->translate("remove"); ?></th>
</tr>

<?php foreach ($this->players as $user) : ?>
<tr style="background-color:<?php 
    echo $this->cycle(array("#F0F0F0","transparent"))->next()?>">
    <td><?php echo $this->escapeHtml($user->getPlayer()->getName());?></td>
    <td><?php echo $this->escapeHtml($user->getLeague()->getNumber());?></td>
    <td><?php echo $this->translate("edit");?></td>
    <td><?php echo $this->translate("remove");?></td>
</tr>
<?php endforeach; ?>
</table>
<?php $this->placeholder('players')->captureEnd(); 

  if($this->players!=null)
      echo $this->placeholder('players');
  else echo $this->placeholder('noseason');

