<div class="blog">
    <?php echo $this->blogWidget;?>
</div>

<div class="row" style="padding 10px;">

    <div class="span2" style="width:auto;">
        <?php echo $this->tableWidget;?>
   </div>

    <div class="span3" style="width:auto;">
        <?php echo $this->resultWidget;?>
        <?php echo $this->rulesWidget;?>
    </div>

    <?php $this->placeholder('nakade')->captureStart();?>
    <h3>Bundesliga Team Nakade</h3>
    <p style="text-align: justify">Unsere Mannschaft <span class="zf-green">Nakade Berlin</span>
        hat die Saison sensationell mit dem ersten Platz beendet und damit den direkten Aufstieg in die dritte Liga
        geschafft. Für den Sieg gab es eine Urkunde, die ihr auf FB bewundern könnt. Auch das einzige Team, gegen
        das wir verloren haben, die Düsseldorfer Steinbeisser, sind aufgestiegen.<br/>
        Weitere Informationen zur Bundesliga findet ihr auf den Seiten des <a href="http://www.dgob.de">DGoB</a></p>
    <a style="margin: 5px 0 10px 0" class="btn btn-success" href="http://www.facebook.com/groups/327762630651096/" target="_blank">Nakade Berlin &raquo;</a>
    <?php $this->placeholder('nakade')->captureEnd();?>

    <?php $this->placeholder('register')->captureStart();?>
    <?php echo $this->registerWidget;?>
    <?php $this->placeholder('register')->captureEnd();?>


    <div class="span4" style="width:300px;">
    <?php

    if (empty($this->registerWidget)) {
        echo $this->placeholder('nakade');
    } else {
        echo $this->placeholder('register');
    }
    ?>
    </div>

</div>



