<div class="hero-unit">
    <h1>Willkommen beim <br/><span class="zf-green">Berliner Baduk Club e.V.</span></h1>
    <p>Diese Vereinsseite wird zZt. bearbeitet. Bitte schau bald wieder rein, um auf dem Laufenden zu bleiben.</p>
     <?php echo $this->blogWidget;?>
</div>

<div class="row">

    <div class="span2" style="width:auto; margin-top:0.5em; margin-right:2em;">
        <?php echo $this->tableWidget;?>
   </div>

    <div class="span3" style="width:auto; margin-top:0.5em; margin-right:2em;">
        <div style="margin-bottom: 30px;"><?php echo $this->resultWidget;?></div>
        <div><?php echo $this->rulesWidget;?></div>
   </div>

    <div class="span4">
        <h2>Bundesliga Team Nakade</h2>
        <p>Unsere Mannschaft <span class="zf-green">Nakade Berlin</span>
            hat die Saison sensationell mit dem ersten Platz beendet und damit den direkten Aufstieg in die dritte Liga
            geschafft. Für den Sieg gab es eine Urkunde, die ihr auf FB bewundern könnt.<br/>
            Auch das einzige Team, gegen das wir verloren haben, die Düsseldorfer Steinbeisser, sind aufgestiegen.<br/>
            Weitere Informationen zur Bundesliga findet ihr auf den Seiten des <a href="http://www.dgob.de">DGoB</a></p>
        <p><a class="btn btn-success" href="http://www.facebook.com/groups/327762630651096/" target="_blank">Nakade Berlin &raquo;</a></p>
    </div>


</div>