<div class="hero-unit">
    <h1>Willkommen beim <br/><span class="zf-green">Berliner Baduk Club e.V.</span></h1>
    <p>Diese Vereinsseite wird zZt. bearbeitet. Bitte schau bald wieder rein, um auf dem Laufenden zu bleiben.</p>
</div>

<div class="row">

    <div class="span4">
        <h2>Bundesliga</h2>
        <p>Unsere Mannschaft <span class="zf-green">Nakade Berlin</span> unter der Leitung von Maurice spielt in ihrer ersten Saison in der 5.Liga. Und das recht erfolgreich! Weitere Informationen zu nächsten Spieltag und unseren Erfolgen findet ihr auf unserer Facebook Seite. Alles zum aktuellem Tabellenstand und der Bundesliga findet ihr auf den Seiten des <a href="http://www.dgob.de">DGoB</a></p>
        <p><a class="btn btn-success" href="http://www.facebook.com/groups/327762630651096/" target="_blank">Nakade Berlin &raquo;</a></p>
    </div>

    <div class="span4">
        <h2 style="color:red;">Neuer Spieltreff</h2>
        <p>Endlich sind wir in Charlottenburg angekommen. In zentraler Lage hinter der Deutschen Oper im Jugendhaus. Ab sofort wird dort jeden Dienstag Go gespielt. Neben dem offziellen Training ist freies Spiel möglich. Gäste sind bei uns gern gesehen.</p>
        <p><a class="btn btn-success" href="<?php echo $this->url('training') ?>" target="_blank">Spieltreff &raquo;</a></p>
   </div>

   <div class="span4">
       <h2>Liga</h2>
       <p>Im Februar startet die erste Liga (1d-3k). Dauer etwa 3 Monate, ca. 5-6 Teilnehmer, 60min (30/10), 7.5 Komi. </br>
           Wir suchen noch Interessenten für eine weitere Liga (4k-8k). Details dazu später hier...</p>
       <p><a class="btn btn-success" href="" target="_blank">Mitglied werden &raquo;</a></p>
   </div>
</div>
