<!-- //module/Authentication/view/auth/success/index.phtml -->

<?php
$this->plugin('translate')->setTranslatorTextDomain('Auth');

$info = $this->translate("You got %number% new messages");
$number = sprintf('<span style="color:red;">%s</span>', $this->noNewMails);
$link = sprintf('<a style="padding-left:15px" href="%s">%s</a>',
    $this->url('message'),
    $this->translate("go to mailbox")
);
$mailInfo = str_replace("%number%", (string) $number, $info);
$textInfo = sprintf('<p style="margin-top:10px;font-weight:bold;">%s%s</p>',
    $mailInfo,
    $link
);

$loginText = $this->translate("Logged in as %name%");
$login = str_replace("%name%", (string) $this->identity()->getUsername(), $loginText);
$logOutLink = sprintf('<a style="padding-left:15px" href="%s">%s</a>',
    $this->url('login/process', array('action'=>'logout')),
    $this->translate('LogOut')
);
$loginInfo = $login . $logOutLink;


if ($user = $this->identity()) {
    echo $loginInfo;
    if ($this->noNewMails > 0) {
        echo $textInfo;
    }
} else {
        echo $this->translate('Not logged in');
}
?>

<hr>

<?php
echo $this->scheduleWidget;

